force-app/main/default/objects/Policy__c/fields/Account_Policy__c.field-meta.xml
<CustomField>
    <fullName>Account_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automobile</fullName>
            </value>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Motorcycle/Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Northbound</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Make__c</fullName>
    <formula>Vehicle_Policy__r.Make__c</formula>
    <label>Vehicle Make</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <formula>Vehicle_Policy__r.Model__c</formula>
    <label>Vehicle Model</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Vehicle_Policy__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle(Policy)</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Vehicle_Year__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Year__c</fullName>
    <formula>Vehicle_Policy__r.Year__c</formula>
    <label>Vehicle Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Owner_Address__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Owner_Address__c</fullName>
    <inlineHelpText>Address of vehicle owner</inlineHelpText>
    <label>Vehicle Owner Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Owner_City__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Owner_City__c</fullName>
    <label>Vehicle Owner City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Owner_Name__c</fullName>
    <label>Vehicle Owner Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Owner_State__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Owner_State__c</fullName>
    <label>Vehicle Owner State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vin__c.field-meta.xml
<CustomField>
    <fullName>Vin__c</fullName>
    <label>Vin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Mex_NorthboundYellowPdf.cls
public class Mex_NorthboundYellowPdf {

    public Policy__c policy{get;set;}
    public string policyId{get;set;}
    public List<Vehicle__c> vehicle{get;set;}
    public Mex_NorthboundYellowPdf(){
        policyId = ApexPages.currentPage().getParameters().get('Id');

        policy = [Select Id, Name, Vehicle_Make__c, Vehicle_Model__c, Vehicle_Year__c, Policy_Type_picklist__c, Account_Policy__r.Name, 
                   Account_Policy__r.Street__c, Account_Policy__r.City__c, Account_Policy__r.State__c, Start_Date__c, End_Date__c, Vehicle_Policy__r.Vehicle_Owner_Name__c, Vehicle_Policy__r.Vehicle_Owner_Address__c, Vehicle_Policy__r.Vehicle_Owner_City__c, 
                  Vehicle_Policy__r.Vehicle_Owner_State__c, Vehicle_Policy__r.Vin__c From policy__c where Id =: policyId limit 1];
    }
}