force-app/main/default/objects/Policy__c/fields/Account_Policy__c.field-meta.xml
<CustomField>
    <fullName>Account_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automobile</fullName>
            </value>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Motorcycle/Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Northbound</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter_picklist__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_picklist__c</fullName>
    <label>Underwriter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chubb</fullName>
            </value>
            <value>
                <fullName>Mapfre</fullName>
            </value>
            <value>
                <fullName>Qualitas</fullName>
            </value>
            <value>
                <fullName>GNP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchTosendQuoteEmail_test.cls
@isTest
public class BatchTosendQuoteEmail_test {
    public static  testMethod void BatchTosendQuoteEmail(){
        TriggerSwitch__c customsetting = new TriggerSwitch__c();
        customsetting.Name = 'PolicyTrigger';
        customsetting.Active__c = false;
        insert customsetting;
        
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        acObj.Affiliate_Number__c = '1234';
        insert acObj;
        
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
       
        set<String> policyIdset = new set<String>();
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy data'; 
        policyrecord.Policy_Type_picklist__c = 'Northbound';
        policyrecord.Term__c ='semi';
        policyrecord.Account_Policy__c = acObj.Id;
        policyrecord.Contact__c = conObj.Id;
        insert policyrecord;
        
        policyIdset.add(policyrecord.Id);
        
        test.startTest();
        //BatchTosendQuoteEmail batchemail = new BatchTosendQuoteEmail(policyIdset, True);
         Database.executeBatch(new BatchTosendQuoteEmail(policyIdset,true));
        test.stopTest();
        
        // batchemail.BatchTosendQuoteEmail();
    }    
        public static  testMethod void BatchTosendQuoteEmail2(){
         TriggerSwitch__c customsetting = new TriggerSwitch__c();
        customsetting.Name = 'PolicyTrigger';
        customsetting.Active__c = false;
        insert customsetting;
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        acObj.Affiliate_Number__c = '1234';
        insert acObj;
            
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
            
        List<Policy__c> policies = new List<Policy__c>();
        set<String> policyIdset = new set<String>();
        for(Integer i =0 ;i<=2; i++){
            Policy__c policyrecord = new policy__c();
            policyrecord.name='policy'+i; 
            policyrecord.Policy_Type_picklist__c = 'Northbound'; 
            policyrecord.Term__c ='semi';
            policyrecord.Account_Policy__c = acObj.Id;
            policyrecord.Contact__c = conObj.Id;           
               
            policies.add(policyrecord);
        }
        insert policies;
            for(Policy__c policyid :policies){
                policyIdset.add(policyid.Id);
            }
        test.startTest();
            Database.executeBatch(new BatchTosendQuoteEmail(policyIdset));
        test.stopTest();
    }
    
    
    public static  testMethod void BatchTosendQuoteEmail3(){
        TriggerSwitch__c customsetting = new TriggerSwitch__c();
        customsetting.Name = 'PolicyTrigger';
        customsetting.Active__c = false;
        insert customsetting;
        
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        acObj.Affiliate_Number__c = '1234';
        insert acObj;
        
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
       
        set<String> policyIdset = new set<String>();
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy data'; 
        policyrecord.Policy_Type_picklist__c = 'Driver License';
        policyrecord.Term__c ='semi';
        policyrecord.Account_Policy__c = acObj.Id;
        policyrecord.Contact__c = conObj.Id;
        insert policyrecord;
        
        policyIdset.add(policyrecord.Id);
        
        test.startTest();
        //BatchTosendQuoteEmail batchemail = new BatchTosendQuoteEmail(policyIdset, True);
         Database.executeBatch(new BatchTosendQuoteEmail(policyIdset,true));
        test.stopTest();
        
        // batchemail.BatchTosendQuoteEmail();
    }  
       public static  testMethod void BatchTosendQuoteEmail4(){
        TriggerSwitch__c customsetting = new TriggerSwitch__c();
        customsetting.Name = 'PolicyTrigger';
        customsetting.Active__c = false;
        insert customsetting;
        
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        acObj.Affiliate_Number__c = '1234';
        insert acObj;
        
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
       
        set<String> policyIdset = new set<String>();
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy data'; 
        policyrecord.Policy_Type_picklist__c = 'Watercraft';
        policyrecord.Term__c ='semi';
        policyrecord.Account_Policy__c = acObj.Id;
        policyrecord.Contact__c = conObj.Id;
        insert policyrecord;
        
        policyIdset.add(policyrecord.Id);
        
        test.startTest();
        //BatchTosendQuoteEmail batchemail = new BatchTosendQuoteEmail(policyIdset, True);
         Database.executeBatch(new BatchTosendQuoteEmail(policyIdset,true));
        test.stopTest();
        
        // batchemail.BatchTosendQuoteEmail();
    }  
       public static  testMethod void BatchTosendQuoteEmail5(){
        TriggerSwitch__c customsetting = new TriggerSwitch__c();
        customsetting.Name = 'PolicyTrigger';
        customsetting.Active__c = false;
        insert customsetting;
        
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        acObj.Affiliate_Number__c = '1234';
        insert acObj;
        
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
       
        set<String> policyIdset = new set<String>();
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy data'; 
        policyrecord.Policy_Type_picklist__c = 'Automobile';
        policyrecord.Underwriter_picklist__c = 'Chubb';
        policyrecord.Term__c ='semi';
        policyrecord.Account_Policy__c = acObj.Id;
        policyrecord.Contact__c = conObj.Id;
        insert policyrecord;
        
        policyIdset.add(policyrecord.Id);
        
        test.startTest();
        //BatchTosendQuoteEmail batchemail = new BatchTosendQuoteEmail(policyIdset, True);
         Database.executeBatch(new BatchTosendQuoteEmail(policyIdset,true));
        test.stopTest();
        
        // batchemail.BatchTosendQuoteEmail();
    }  
       public static  testMethod void BatchTosendQuoteEmail6(){
        TriggerSwitch__c customsetting = new TriggerSwitch__c();
        customsetting.Name = 'PolicyTrigger';
        customsetting.Active__c = false;
        insert customsetting;
        
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        acObj.Affiliate_Number__c = '1234';
        insert acObj;
        
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
       
        set<String> policyIdset = new set<String>();
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy data'; 
        policyrecord.Policy_Type_picklist__c = 'Automobile';
        policyrecord.Underwriter_picklist__c = 'Mapfre';
        policyrecord.Term__c ='semi';
        policyrecord.Account_Policy__c = acObj.Id;
        policyrecord.Contact__c = conObj.Id;
        insert policyrecord;
        
        policyIdset.add(policyrecord.Id);
        
        test.startTest();
        //BatchTosendQuoteEmail batchemail = new BatchTosendQuoteEmail(policyIdset, True);
         Database.executeBatch(new BatchTosendQuoteEmail(policyIdset,true));
        test.stopTest();
        
        // batchemail.BatchTosendQuoteEmail();
    }  
       public static  testMethod void BatchTosendQuoteEmail7(){
        TriggerSwitch__c customsetting = new TriggerSwitch__c();
        customsetting.Name = 'PolicyTrigger';
        customsetting.Active__c = false;
        insert customsetting;
        
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        acObj.Affiliate_Number__c = '1234';
        insert acObj;
        
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
       
        set<String> policyIdset = new set<String>();
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy data'; 
        policyrecord.Policy_Type_picklist__c = 'Automobile';
        policyrecord.Underwriter_picklist__c = 'Qualitas';
        policyrecord.Term__c ='semi';
        policyrecord.Account_Policy__c = acObj.Id;
        policyrecord.Contact__c = conObj.Id;
        insert policyrecord;
        
        policyIdset.add(policyrecord.Id);
        
        test.startTest();
        //BatchTosendQuoteEmail batchemail = new BatchTosendQuoteEmail(policyIdset, True);
         Database.executeBatch(new BatchTosendQuoteEmail(policyIdset,true));
        test.stopTest();
        
        // batchemail.BatchTosendQuoteEmail();
    }  
       public static  testMethod void BatchTosendQuoteEmail8(){
        TriggerSwitch__c customsetting = new TriggerSwitch__c();
        customsetting.Name = 'PolicyTrigger';
        customsetting.Active__c = false;
        insert customsetting;
        
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        acObj.Affiliate_Number__c = '1234';
        insert acObj;
        
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
       
        set<String> policyIdset = new set<String>();
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy data'; 
        policyrecord.Policy_Type_picklist__c = 'RV';
        policyrecord.Underwriter_picklist__c = 'Chubb';
        policyrecord.Term__c ='semi';
        policyrecord.Account_Policy__c = acObj.Id;
        policyrecord.Contact__c = conObj.Id;
        insert policyrecord;
        
        policyIdset.add(policyrecord.Id);
        
        test.startTest();
        //BatchTosendQuoteEmail batchemail = new BatchTosendQuoteEmail(policyIdset, True);
         Database.executeBatch(new BatchTosendQuoteEmail(policyIdset,true));
        test.stopTest();
        
        // batchemail.BatchTosendQuoteEmail();
    }  
    public static  testMethod void BatchTosendQuoteEmail9(){
        TriggerSwitch__c customsetting = new TriggerSwitch__c();
        customsetting.Name = 'PolicyTrigger';
        customsetting.Active__c = false;
        insert customsetting;
        
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        acObj.Affiliate_Number__c = '1234';
        insert acObj;
        
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
       
        set<String> policyIdset = new set<String>();
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy data'; 
        policyrecord.Policy_Type_picklist__c = 'RV';
        policyrecord.Underwriter_picklist__c = 'Mapfre';
        policyrecord.Term__c ='semi';
        policyrecord.Account_Policy__c = acObj.Id;
        policyrecord.Contact__c = conObj.Id;
        insert policyrecord;
        
        policyIdset.add(policyrecord.Id);
        
        test.startTest();
        //BatchTosendQuoteEmail batchemail = new BatchTosendQuoteEmail(policyIdset, True);
         Database.executeBatch(new BatchTosendQuoteEmail(policyIdset,true));
        test.stopTest();
        
        // batchemail.BatchTosendQuoteEmail();
    }  
    public static  testMethod void BatchTosendQuoteEmail10(){
        TriggerSwitch__c customsetting = new TriggerSwitch__c();
        customsetting.Name = 'PolicyTrigger';
        customsetting.Active__c = false;
        insert customsetting;
        
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        acObj.Affiliate_Number__c = '1234';
        insert acObj;
        
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
       
        set<String> policyIdset = new set<String>();
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy data'; 
        policyrecord.Policy_Type_picklist__c = 'RV';
        policyrecord.Underwriter_picklist__c = 'Qualitas';
        policyrecord.Term__c ='semi';
        policyrecord.Account_Policy__c = acObj.Id;
        policyrecord.Contact__c = conObj.Id;
        insert policyrecord;
        
        policyIdset.add(policyrecord.Id);
        
        test.startTest();
        //BatchTosendQuoteEmail batchemail = new BatchTosendQuoteEmail(policyIdset, True);
         Database.executeBatch(new BatchTosendQuoteEmail(policyIdset,true));
        test.stopTest();
        
        // batchemail.BatchTosendQuoteEmail();
    }  
    public static  testMethod void BatchTosendQuoteEmail11(){
        TriggerSwitch__c customsetting = new TriggerSwitch__c();
        customsetting.Name = 'PolicyTrigger';
        customsetting.Active__c = false;
        insert customsetting;
        
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        acObj.Affiliate_Number__c = '1234';
        insert acObj;
        
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
       
        set<String> policyIdset = new set<String>();
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy data'; 
        policyrecord.Policy_Type_picklist__c = 'Motorcycle/Street Legal ATV';
        policyrecord.Underwriter_picklist__c = 'Mapfre';
        policyrecord.Term__c ='semi';
        policyrecord.Account_Policy__c = acObj.Id;
        policyrecord.Contact__c = conObj.Id;
        insert policyrecord;
        
        policyIdset.add(policyrecord.Id);
        
        test.startTest();
        //BatchTosendQuoteEmail batchemail = new BatchTosendQuoteEmail(policyIdset, True);
         Database.executeBatch(new BatchTosendQuoteEmail(policyIdset,true));
        test.stopTest();
        
        // batchemail.BatchTosendQuoteEmail();
    }  
}