force-app/main/default/objects/Policy__c/fields/Account_Policy__c.field-meta.xml
<CustomField>
    <fullName>Account_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Created_At__c.field-meta.xml
<CustomField>
    <fullName>Created_At__c</fullName>
    <label>Created At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/End_at__c.field-meta.xml
<CustomField>
    <fullName>End_at__c</fullName>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PoliciesTrigger_Test.cls
/*--------------------------------------------------------------------------
* Author: Techila Global Services Pvt Ltd.
* Test Class Name: PoliciesTrigger_Test
* Created Date: 23-November-2017
----------------------------------------------------------------------------*/

@isTest
public class PoliciesTrigger_Test {
	public static testmethod void PolicyRenewalEmailAlerttest(){
		Account objAccount =new Account();
		objAccount.Name = 'test';
		objAccount.Email__c = 'test@test.com';
        objAccount.Created_At__c = System.today();
		insert objAccount;
		
		Contact objcontact =new Contact();
		objcontact.FirstName = 'Test';
		objcontact.LastName = 'Name';
		objcontact.Phone = '1-555-555-55-55';
		objcontact.Email = 'email@sample.com';
		insert objcontact;
	  	
        TriggerSwitch__c objTriggerSwitch = new TriggerSwitch__c();
        objTriggerSwitch.Name = 'PolicyTrigger';
        insert objTriggerSwitch;
        
		Policy__c objPolicy =new Policy__c();
		objPolicy.Name = 'test';
		//objPolicy.Contact__c = objcontact.Id;
		objPolicy.Account_Policy__c = objAccount.Id;
		objPolicy.End_at__c=system.today();        	
		insert objPolicy;     
        
        Policy__c objPolicy1 =new Policy__c();
		objPolicy1.Name = 'test';
		objPolicy1.Contact__c = objcontact.Id;
		objPolicy1.Account_Policy__c = objAccount.Id;
	    objPolicy1.End_at__c=system.today();        	
		insert objPolicy1;  
		
	}    
}