force-app/main/default/objects/Policy__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies (Agency)</relationshipLabel>
    <relationshipName>Agency</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automobile</fullName>
            </value>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Motorcycle/Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Northbound</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Term_days__c.field-meta.xml
<CustomField>
    <fullName>Term_days__c</fullName>
    <label>Term_Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Third_Party_Bodily_Injury__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Bodily_Injury__c</fullName>
    <label>Third Party Bodily Injury</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Third_Party_Bodily_Injury</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Underwriter__c</fullName>
    <label>Underwriter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chubb</fullName>
            </value>
            <value>
                <fullName>Mapfre</fullName>
            </value>
            <value>
                <fullName>Qualitas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Vehicle_type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_type__c</fullName>
    <label>Vehicle_Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <formula>BLANKVALUE(Lead__r.Agency__r.Id__c, Contact__r.Agency__r.Id__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Limited</fullName>
            </value>
            <value>
                <fullName>Max</fullName>
            </value>
            <value>
                <fullName>LiabilityTheft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/End_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>End_Date_for_Coverage__c</fullName>
    <label>End Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Liability</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Medical</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Medical_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Medical_Coverage__c</fullName>
    <label>Medical Coverage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Property_Damage_Liability__c.field-meta.xml
<CustomField>
    <fullName>Property_Damage_Liability__c</fullName>
    <label>Property Damage Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Property_Damage_Liability</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Value__c.field-meta.xml
<CustomField>
    <fullName>Quote_Value__c</fullName>
    <label>Quote Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuotePdfJson__c.field-meta.xml
<CustomField>
    <fullName>QuotePdfJson__c</fullName>
    <label>QuotePdfJson</label>
    <length>37000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Start_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_for_Coverage__c</fullName>
    <label>Start Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Term_Days__c.field-meta.xml
<CustomField>
    <fullName>Term_Days__c</fullName>
    <label>Term Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Territory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Policy_Type_picklist__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

buho-site/main/default/classes/Mex_ShowSelectedQuotePdf.cls
public without sharing class Mex_ShowSelectedQuotePdf {
  public string quoteId;
  public List<Map<String, Object>> coveredBenefits { get; set; }
  public Quote__c quoteDetail { get; set; }
  public string startTime { get; set; }
  public string endTime { get; set; }
  public string name { get; set; }
  public Boolean isBuho { get; set; }

  public Mex_ShowSelectedQuotePdf() {
    quoteId = ApexPages.currentPage().getParameters().get('Id');

    quoteDetail = [
      SELECT
        Id,
        Name,
        Start_Date_for_Coverage__c,
        End_Date_for_Coverage__c,
        Start_Time__c,
        Term_Days__c,
        Policy_Type_picklist__c,
        Quote_Value__c,
        Third_Party_Bodily_Injury__c,
        End_Time__c,
        Vehicle_Type__c,
        Property_Damage_Liability__c,
        Lead__r.LeadSource,
        Liability__c,
        Territory__c,
        Medical__c,
        Coverage__c,
        Medical_Coverage__c,
        Underwriter__c,
        QuotePdfJson__c,
        Lead__r.Name,
        Contact__c,
        Contact__r.Name,
        Contact__r.Agency__c,
        Contact__r.Agency__r.Name,
        Lead__c,
        Lead__r.Agency__r.Name
      FROM Quote__c
      WHERE Id = :quoteId
      LIMIT 1
    ];
    Apexpages.currentPage()
      .getHeaders()
      .put(
        'content-disposition',
        'inline; filename=Mexinsurance-' + quoteDetail.Underwriter__c + '-Quote.pdf'
      );
    if (
      (String.isNotBlank(quoteDetail.Lead__r.LeadSource) &&
      quoteDetail.Lead__r.LeadSource.contains('Buho')) ||
      (quoteDetail.Contact__c != null &&
      String.isNotBlank(quoteDetail.Contact__r.Agency__r.Name) &&
      quoteDetail.Contact__r.Agency__r.Name.contains('Buho')) ||
      (quoteDetail.Lead__c != null &&
      String.isNotBlank(quoteDetail.Lead__r.Agency__r.Name) &&
      quoteDetail.Lead__r.Agency__r.Name.contains('Buho'))
    ) {
      isBuho = true;
    } else {
      isBuho = false;
    }

    if (quoteDetail.Lead__r.Name == null || quoteDetail.Lead__r.Name == '') {
      name = quoteDetail.Contact__r.Name;
    } else {
      name = quoteDetail.Lead__r.Name;
    }

    System.debug('QuoteList--->?///////-->' + quoteDetail.Lead__r.Name);
    coveredBenefits = new List<Map<String, Object>>();

    if (String.isNotBlank(quoteDetail.QuotePdfJson__c)) {
      Map<String, Object> allData = (Map<String, Object>) JSON.deserializeUntyped(
        quoteDetail.QuotePdfJson__c
      );
      String uw = quoteDetail.Underwriter__c; // "Chubb", "Mapfre", "Qualitas"
      if (allData.containsKey(uw)) {
        Map<String, Object> underwriterMap = (Map<String, Object>) allData.get(uw);
        for (String covName : underwriterMap.keySet()) {
          Map<String, Object> covDetail = (Map<String, Object>) underwriterMap.get(covName);

          //coveredBenefits.add(row);
          system.debug('Title :: ' + covName);
          system.debug('is title in the map :: ' + covDetail.containsKey('Title'));
          //stem.debug(' Is the tile coderdd :: '+ String.valueOf(covDetail.get('Title')).startsWith('Covered'));

          if (
            covDetail.containsKey('Title') &&
            !String.valueOf(covDetail.get('Title')).contains('Not Covered') &&
            !String.valueOf(covDetail.get('Title')).contains('Not Included')
          ) {
            Map<String, Object> row = new Map<String, Object>();
            row.put('Coverage', covName);
            // row.put('Order', covDetail.get('Order'));
            row.put('Title', covDetail.get('Title'));
            row.put('Description', covDetail.get('Description'));
            row.put('Image', covDetail.get('Image'));
            coveredBenefits.add(row);
          } else if (!covDetail.containsKey('Title')) {
            Map<String, Object> row = new Map<String, Object>();
            row.put('Coverage', covName);
            // row.put('Order', covDetail.get('Order'));
            row.put('Title', '');
            row.put('Description', covDetail.get('Description'));
            row.put('Image', covDetail.get('Image'));
            coveredBenefits.add(row);
          }

          //system.debug(' this is the current value :: '+ row);
        }
      }
    }
    system.debug('coveredBenefits:: ' + coveredBenefits);
    if (quoteDetail.Start_Time__c != null) {
      Integer strtHour = quoteDetail.Start_Time__c.hour();
      Integer strtmin = quoteDetail.Start_Time__c.minute();

      string strHour = strtHour.format();
      string shift = ' AM';
      if (strtHour > 12) {
        shift = ' PM';
      } else {
        strHour = '0' + strtHour.format();
      }

      startTime = strHour + ':' + string.valueOf(strtmin) + shift;
    }
    if (quoteDetail.End_Time__c != null) {
      Integer endHour = quoteDetail.Start_Time__c.hour();
      Integer endmin = quoteDetail.Start_Time__c.minute();

      string strHour = endHour.format();
      string shift = ' AM';
      if (endHour > 12) {
        shift = ' PM';
      } else {
        strHour = '0' + endHour.format();
      }

      endTime = strHour + ':' + string.valueOf(endmin) + shift;
      // endTime = string.valueOf(quoteDetail.End_Time__c);
    }
    // }
  }
}