force-app/main/default/objects/Policy__c/fields/Auto_renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Auto_renew_card__c.field-meta.xml
<CustomField>
    <fullName>Auto_renew_card__c</fullName>
    <label>Auto renew card</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Auto_Renew_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Renew Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/I_V_A_Mex_Tax__c.field-meta.xml
<CustomField>
    <fullName>I_V_A_Mex_Tax__c</fullName>
    <label>I.V.A. / Mex. Tax:</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Liability_Payment__c.field-meta.xml
<CustomField>
    <fullName>Liability_Payment__c</fullName>
    <formula>Quote_c__r.Liability_Payment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Liability Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Medical_Payment__c.field-meta.xml
<CustomField>
    <fullName>Medical_Payment__c</fullName>
    <formula>Quote_c__r.Medical_Payment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Medical Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Net_Premium__c.field-meta.xml
<CustomField>
    <fullName>Net_Premium__c</fullName>
    <label>Net Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Physical_Damage__c.field-meta.xml
<CustomField>
    <fullName>Physical_Damage__c</fullName>
    <formula>Quote_c__r.Physical_Damage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Physical Damage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automobile</fullName>
            </value>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Motorcycle/Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Northbound</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Quote_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote (c)</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Renew_Payment_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Renew_Payment_Profile_Id__c</fullName>
    <label>Renew Payment Profile Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Term_days__c.field-meta.xml
<CustomField>
    <fullName>Term_days__c</fullName>
    <label>Term_Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Updated_Quote_Json__c.field-meta.xml
<CustomField>
    <fullName>Updated_Quote_Json__c</fullName>
    <label>Updated Quote Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Broker_Policy_Fee__c.field-meta.xml
<CustomField>
    <fullName>Broker_Policy_Fee__c</fullName>
    <label>Broker/Policy Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Limited</fullName>
            </value>
            <value>
                <fullName>Max</fullName>
            </value>
            <value>
                <fullName>LiabilityTheft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/End_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>End_Date_for_Coverage__c</fullName>
    <label>End Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Is_there_a_driver_under_21__c.field-meta.xml
<CustomField>
    <fullName>Is_there_a_driver_under_21__c</fullName>
    <label>Is there a driver under 21</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
            <value>
                <fullName>true</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Is_this_a_Rental_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Is_this_a_Rental_Vehicle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is this a Rental Vehicle?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Liability</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Liability_Payment__c.field-meta.xml
<CustomField>
    <fullName>Liability_Payment__c</fullName>
    <label>Liability Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Medical</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Medical_Payment__c.field-meta.xml
<CustomField>
    <fullName>Medical_Payment__c</fullName>
    <label>Medical Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Physical_Damage__c.field-meta.xml
<CustomField>
    <fullName>Physical_Damage__c</fullName>
    <label>Physical Damage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Platinum_Endorsment__c.field-meta.xml
<CustomField>
    <fullName>Platinum_Endorsment__c</fullName>
    <label>Platinum Endorsement</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Status__c.field-meta.xml
<CustomField>
    <fullName>Quote_Status__c</fullName>
    <label>Quote Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Policy Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Value__c.field-meta.xml
<CustomField>
    <fullName>Quote_Value__c</fullName>
    <label>Quote Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Salvage_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Salvage_Vehicle__c</fullName>
    <label>Salvage Vehicle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Start_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_for_Coverage__c</fullName>
    <label>Start Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>90 Day</fullName>
            </value>
            <value>
                <fullName>Semi-Annual(Half a Year)</fullName>
            </value>
            <value>
                <fullName>Annual(One Year)</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Term_Days__c.field-meta.xml
<CustomField>
    <fullName>Term_Days__c</fullName>
    <label>Term Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PolicyAutoRenewQuoteGenerateBatch.cls
public class PolicyAutoRenewQuoteGenerateBatch implements Database.batchable<Sobject>,Database.Stateful , Database.AllowsCallouts{
    
    public Map<Id, Quote__c> policyIdVsQuote = new Map<Id, Quote__c>();
    public Set<Id> policyIdSet = new Set<Id>();
    public PolicyAutoRenewQuoteGenerateBatch(Set<Id> policyIdSet) {
        policyIdVsQuote = new Map<Id, Quote__c>();
        this.policyIdSet = policyIdSet;
    }
    
    public Database.queryLocator start(Database.batchableContext BC){ 
        System.debug('Start Policy Renew Batch');
        date todaysDate = date.today();
        String query = 'SELECT id, Term__c, Term_days__c, Auto_renew__c, End_Date__c, Start_Date__c, Quote_c__c, Policy_Type_picklist__c,Contact__c,Auto_renew_card__c,Renew_Payment_Profile_Id__c,Auto_Renew_Confirmed__c,Updated_Quote_Json__c  from Policy__c WHERE Id IN: policyIdSet LIMIT 50000';

        System.debug('query'+query);
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Policy__c> policyList){
        System.debug('Policy List - '+ policyList);
        
        Set<Id> quoteIdSet = new Set<Id>();
        Map<Id,Quote__c> queryQuote = new Map<Id,Quote__c>();
        
        if(policyList.size() > 0){
            for(Policy__c policy :policyList){
                quoteIdSet.add(policy.Quote_c__c);
            }
        }
        
        if(quoteIdSet.size() > 0){
            List<Quote__c> quoteList = [SELECT Account__c, Broker_Policy_Fee__c, Contact__c, Coverage__c, End_Date_for_Coverage__c, End_Time__c, 
                                        I_V_A_Mex_Tax__c, Is_there_a_driver_under_21__c, Is_this_a_Rental_Vehicle__c, Liability_Payment__c, Liability__c, 
                                        Medical__c, Medical_Payment__c, Net_Premium__c, OwnerId, Physical_Damage__c, Platinum_Endorsment__c, Policy_Type_picklist__c, 
                                        Quote_Status__c, Quote_Value__c, Salvage_Vehicle__c, Start_Date_for_Coverage__c, Start_Time__c, Surcharge__c, Term_Days__c, 
                                        Term__c, Territory__c, Total_Theft_Payment__c, Towed_Unit__c, Trailering__c, Underwriter__c, Vehicle_Deductible_Collision__c, 
                                        Vehicle_Deductible_Comprehensive__c, Vehicle_Make__c, Vehicle_Model__c, Vehicle_Sub_type__c, Vehicle_Type__c, Vehicle_Value__c, 
                                        Vehicle_Year__c, Vehicle_used_for_Business_Purposes__c FROM Quote__c where id IN: quoteIdSet];
            
            if(quoteList.size() > 0){
                for (Quote__c quote : quoteList) {
                    queryQuote.put(quote.Id, quote);
                }
            }
        }
        
        if(policyList.size() > 0){
            for (Policy__c policy : policyList) {
                String oldquoteId = policy.Quote_c__c;
                Map<String, Object> quoteDetails = new Map<String, Object>();
                if(policy.Updated_Quote_Json__c != null){
                    quoteDetails = (Map<String, Object>)JSON.deserializeUntyped(policy.Updated_Quote_Json__c);
                }
                
                Quote__c quoteRecord = queryQuote.get(oldquoteId).clone();
                quoteRecord.Id = null;
                
                if (quoteDetails.containsKey('Vehicle_Value__c')) {
                    Object vehicleValue = quoteDetails.get('Vehicle_Value__c');
                    
                    if (vehicleValue instanceof Decimal) {
                        quoteRecord.Vehicle_Value__c = (Decimal)vehicleValue;
                    } else if (vehicleValue instanceof String) {
                        quoteRecord.Vehicle_Value__c = Decimal.valueOf((String)vehicleValue);
                    }
                }
                
                //if(quoteDetails.containskey('Vehicle_Value__c')){
                //    quoteRecord.Vehicle_Value__c = Decimal.valueOf(quoteDetails.get('Vehicle_Value__c'));
                //}
                
                if(quoteDetails.containskey('Liability__c')){
                    quoteRecord.Liability__c = String.valueOf(quoteDetails.get('Liability__c'));
                }
                
                if(quoteDetails.containskey('Medical__c')){
                    quoteRecord.Medical__c = String.valueOf(quoteDetails.get('Medical__c'));
                }
                
                insert quoteRecord;
                policyIdVsQuote.put(policy.Id, quoteRecord);
            }
        }
        System.debug('policyIdVsQuote-->'+policyIdVsQuote);
        //List<Quote__c> newQuoteRecords = new List<Quote__c>(policyIdVsQuote.values());
        
    }
    
    public void finish(Database.BatchableContext Bc) {
        System.debug('Finish Policy Renew Batch ->');
        System.debug('policyIdVsQuote-->'+policyIdVsQuote);
        if (policyIdVsQuote.size() > 0) {
            Database.executeBatch(new PolicyAutoRenewGetTransaction(policyIdVsQuote),4);
        } else {
            System.debug('Error: The Quote size is Zero');
        }
    }
    
}