force-app/main/default/objects/Policy__c/fields/Auto_renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Auto_renew_card__c.field-meta.xml
<CustomField>
    <fullName>Auto_renew_card__c</fullName>
    <label>Auto renew card</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Auto_Renew_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Renew Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Net_Premium__c.field-meta.xml
<CustomField>
    <fullName>Net_Premium__c</fullName>
    <label>Net Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automobile</fullName>
            </value>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Motorcycle/Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Northbound</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Quote_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote (c)</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Renew_Payment_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Renew_Payment_Profile_Id__c</fullName>
    <label>Renew Payment Profile Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status_picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Term_days__c.field-meta.xml
<CustomField>
    <fullName>Term_days__c</fullName>
    <label>Term_Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Total_Premium_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Premium_Amount__c</fullName>
    <formula>IF( NOT(ISBLANK(Total_Transaction_Amount__c)), Total_Transaction_Amount__c ,0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Premium Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Total_Theft_Payment__c.field-meta.xml
<CustomField>
    <fullName>Total_Theft_Payment__c</fullName>
    <formula>Quote_c__r.Total_Theft_Payment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Theft Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter_picklist__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_picklist__c</fullName>
    <label>Underwriter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chubb</fullName>
            </value>
            <value>
                <fullName>Mapfre</fullName>
            </value>
            <value>
                <fullName>Qualitas</fullName>
            </value>
            <value>
                <fullName>GNP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Updated_Quote_Json__c.field-meta.xml
<CustomField>
    <fullName>Updated_Quote_Json__c</fullName>
    <label>Updated Quote Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Vehicle_Value__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Value__c</fullName>
    <formula>Vehicle_Policy__r.Value__c</formula>
    <label>Vehicle Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/End_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>End_Date_for_Coverage__c</fullName>
    <label>End Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Liability</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Medical</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Start_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_for_Coverage__c</fullName>
    <label>Start Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>90 Day</fullName>
            </value>
            <value>
                <fullName>Semi-Annual(Half a Year)</fullName>
            </value>
            <value>
                <fullName>Annual(One Year)</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Term_Days__c.field-meta.xml
<CustomField>
    <fullName>Term_Days__c</fullName>
    <label>Term Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Total_Theft_Payment__c.field-meta.xml
<CustomField>
    <fullName>Total_Theft_Payment__c</fullName>
    <label>Total Theft Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Vehicle_Value__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Value__c</fullName>
    <label>Vehicle Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PolicyRenewAlertController.cls
public without sharing class PolicyRenewAlertController {
    
    @AuraEnabled
    public static String fetchPolicy(String policyId){
        try{
            System.debug('policyIds'+policyId);
            
            Map<string,Object> typeVsdays = new Map<string,Object>();
            List<policy__c> policyList = [SELECT Id, Name ,End_Date__c, Policy_Type_picklist__c,Status_picklist__c , Start_Date__c,Total_Premium_Amount__c,Term__c,Quote_c__c, Renew_Payment_Profile_Id__c , Auto_renew_card__c, Auto_renew__c FROM Policy__c WHERE ID =: policyId LIMIT 1];
            date todaysDate = date.today();
            
            System.debug('policyList'+policyList);
            System.debug('todaysDate'+todaysDate);
            
            for(policy__c each : policyList){
                typeVsdays.put('PolicyType' , each.Policy_Type_picklist__c);
                typeVsdays.put('Status' , each.Status_picklist__c );
                typeVsdays.put('TotalPremium' , each.Total_Premium_Amount__c);
                typeVsdays.put('QuoteID' , each.Quote_c__c  );
                typeVsdays.put('TermDays' , each.Term__c  );
                typeVsdays.put('Autorenew' , each.Auto_renew__c  );
                typeVsdays.put('paymentProfileId' , each.Renew_Payment_Profile_Id__c  );
                if(each.Term__c == 'Daily' && each.Start_Date__c <= todaysDate){
                    typeVsdays.put('isDailyPolicy' , 'True');
                }
                
                if(each.Start_Date__c <= todaysDate && each.End_Date__c >= todaysDate){
					Integer dateDifference = todaysDate.daysBetween(each.End_Date__c);
                    Integer runningDateDifference = each.Start_Date__c.daysBetween(todaysDate);
                    String dateDiff = String.valueOf(dateDifference);
                    String runningDiff = String.valueOf(runningDateDifference);
                    
                    typeVsdays.put('isRunningDays' , 'True');
                    typeVsdays.put('DaysLeft' , dateDiff);
                    typeVsdays.put('RunningDays' , runningDiff);
                    
                    System.debug('Name ' +each.name + '  Start Date' +each.Start_Date__c +'   DateDifference'+dateDifference);
                    
                }else if(each.Start_Date__c >= todaysDate){
                    Integer dateDifference = todaysDate.daysBetween(each.Start_Date__c);
                    String dateDiff = String.valueOf(dateDifference);
                    
                    typeVsdays.put('isTerminationAmount' , 'True');
                    typeVsdays.put('isStaringDays' , 'True');
                    typeVsdays.put('StartingDays' , dateDiff);
                    
                    System.debug('Name ' +each.name + '   Start Date' +each.Start_Date__c +'    NOT STARTED ---DateDifference--'+dateDifference);
                    
                }else{
                    typeVsdays.put('isExpired' , 'True');
                    System.debug('EXPIRED Name  ' +each.name + '   Start Date' +each.Start_Date__c );
                }
            }
            
            return JSON.serialize(typeVsdays);
        }catch(exception e){
            System.debug('Error -'+ e.getMessage() +' at line - '+e.getLineNumber());
            return 'ERROR';
        }
    }
    
    @AuraEnabled
    public static void saveRenewDetails(String cardJson , String policyId, String profileId, Boolean autoRenew){
        
        if(autoRenew == true && (policyId != null || policyId != '' )){
            Policy__c policy = new Policy__c();
        
            policy.Id = policyId;
            policy.Auto_renew__c = true;
            policy.Auto_renew_card__c = cardJson;
            policy.Renew_Payment_Profile_Id__c = profileId;
            
            System.debug('Policy Details--'+policy);
            update policy; 
            
        }else if(autoRenew == false && (policyId != null || policyId != '' )){
             Policy__c policy = new Policy__c();
        
            policy.Id = policyId;
            policy.Auto_renew__c = false;
            policy.Auto_renew_card__c = '';
            policy.Renew_Payment_Profile_Id__c = '';
            
            System.debug('Policy Details--'+policy);
            update policy; 
        }
    }
    
    @AuraEnabled
    public static List<Policy__c> fetchQuoteDetails(String policyId){
        if(policyId != null){
            List<Policy__c> policyList = new List<Policy__c>();
            policyList = [SELECT Policy_Type_picklist__c, Underwriter_picklist__c, Updated_Quote_Json__c, Auto_Renew_Confirmed__c, Quote_c__c,Quote_c__r.Start_Date_for_Coverage__c, Quote_c__r.End_Date_for_Coverage__c, Quote_c__r.Term_Days__c, 
                          Quote_c__r.Medical__c, Quote_c__r.Liability__c, Quote_c__r.Net_Premium__c, Quote_c__r.Total_Theft_Payment__c,Quote_c__r.Vehicle_Value__c 
                          FROM Policy__c WHERE id =: policyId LIMIT 1];
            return policyList;
        }else{
            return null;
        }
        
    }
    
    @AuraEnabled
    public static void updatedQuoteToPolicy(String quoteJson, string policyId){
        System.debug('updatedQuoteToPolicy--');
        if(quoteJson != null && policyId != null){
            Policy__c policy = new Policy__c();
            policy.Id = policyId;
            policy.Updated_Quote_Json__c = quoteJson;
            policy.Auto_Renew_Confirmed__c = true;
            update policy;
            
            String orgWideEmailAddressLabel = System.Label.userEmailForAutorenew;
            Id orgWideEmailAddress = null;
            System.debug('policy'+policy);
            System.debug('orgWideEmailAddressLabel'+orgWideEmailAddressLabel);
            
            Policy__c policyData = [SELECT Id,Name,Contact__c,Contact__r.Name,End_date__c FROM Policy__c WHERE ID =: policy.Id LIMIT 1];
            EmailTemplate emailTemplate = [SELECT Id,HtmlValue,Body,Subject FROM EmailTemplate WHERE DeveloperName = 'PolicyAutoRenewalApproved' LIMIT 1];
            if(orgWideEmailAddressLabel != null){
                orgWideEmailAddress = [SELECT Id FROM OrgWideEmailAddress WHERE DisplayName =:orgWideEmailAddressLabel  LIMIT 1].Id;
            }
            

            String htmlBody = emailTemplate.HtmlValue;
            String plainBody = emailTemplate.Body;
            System.debug('policyData'+policyData);
            htmlBody = htmlBody.replace('{!Contact.Name}', policyData.Contact__r.Name);
            htmlBody = htmlBody.replace('{!Policy__c.Id}', policyData.Id);
            htmlBody = htmlBody.replace('{!EndDate}', String.valueof(policyData.End_Date__c));
            plainBody = plainBody.replace('{!EndDate}', String.valueof(policyData.End_Date__c));
            plainBody = plainBody.replace('{!Contact.Name}', policyData.Contact__r.Name);
            plainBody = plainBody.replace('{!Policy__c.Id}', policyData.Id);
            
            List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
            
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setTemplateId(emailTemplate.Id);
            email.setTargetObjectId(policyData.Contact__c);
            email.setWhatId(policyData.id);
            email.setHtmlBody(htmlBody);
            email.setPlainTextBody(plainBody);
            email.setSubject(emailTemplate.Subject);
            email.setOrgWideEmailAddressId(orgWideEmailAddress);
            emails.add(email);
            System.debug('emails'+emails);
            
            if (!emails.isEmpty()) {
                Messaging.sendEmail(emails);
            }
        }
        
    }
    
    @AuraEnabled
    public static void updatePolicyOnCardRemove(String paymentId){
        List<Policy__c> policyList = new List<Policy__c>();
        List<Policy__c> updatePolicyList = new List<Policy__c>();
        policyList = [SELECT Id, Name,Auto_renew__c, Auto_renew_card__c, Renew_Payment_Profile_Id__c FROM policy__c WHERE Contact__c = :ContactService.contactId AND Auto_renew__c = true AND Renew_Payment_Profile_Id__c =: paymentId];
        System.debug('policyList---'+policyList);
        
        if(policyList.Size() > 0){
            for(policy__c polObj : policyList){
                Policy__c policy = new Policy__c();
                policy.Id = polObj.id;
                policy.Auto_renew__c = False;
                policy.Auto_renew_card__c = '';
                policy.Renew_Payment_Profile_Id__c = '';
                policy.Auto_Renew_Confirmed__c = false;
                policy.Updated_Quote_Json__c = '';
                updatePolicyList.add(policy);
            }
        }
        
        if(updatePolicyList.Size() > 0){
            update updatePolicyList;
        }
        
    }

}