force-app/main/default/objects/Policy__c/fields/Auto_renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Auto_renew_card__c.field-meta.xml
<CustomField>
    <fullName>Auto_renew_card__c</fullName>
    <label>Auto renew card</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Auto_Renew_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Renew Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automobile</fullName>
            </value>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Motorcycle/Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Northbound</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Quote_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote (c)</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Renew_Payment_Profile_Id__c.field-meta.xml
<CustomField>
    <fullName>Renew_Payment_Profile_Id__c</fullName>
    <label>Renew Payment Profile Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Term_days__c.field-meta.xml
<CustomField>
    <fullName>Term_days__c</fullName>
    <label>Term_Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Updated_Quote_Json__c.field-meta.xml
<CustomField>
    <fullName>Updated_Quote_Json__c</fullName>
    <label>Updated Quote Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>90 Day</fullName>
            </value>
            <value>
                <fullName>Semi-Annual(Half a Year)</fullName>
            </value>
            <value>
                <fullName>Annual(One Year)</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Term_Days__c.field-meta.xml
<CustomField>
    <fullName>Term_Days__c</fullName>
    <label>Term Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PolicyAutoRenewGetTransaction.cls
public class PolicyAutoRenewGetTransaction implements Database.batchable<Sobject> ,Database.Stateful, Database.AllowsCallouts {
    
    public Map<String,object> policyIdsVsTransaction = new Map<String, object>();
    public Map<Id, Quote__c> policyIdVsQuote = new Map<Id, Quote__c>();
    public Set<String> policyIdsSet = new Set<String>();
    public Map<String,AuthorizeNetClient.CreateTransactionRequest> policyVsRequest = new Map<String,AuthorizeNetClient.CreateTransactionRequest>();
    public Map<String,AuthorizeNetClient.CreateTransactionResponse> policyVsResponse = new Map<String,AuthorizeNetClient.CreateTransactionResponse>();
    public Map<Id,Object> failedTransacation = new Map<Id,Object>();
    
    public PolicyAutoRenewGetTransaction(Map<Id, Quote__c> quotes) {
        this.policyIdVsQuote = quotes;
        this.policyIdsSet = new Set<String>(); 
        this.policyIdsVsTransaction = new Map<String, object>();
        this.policyVsRequest = new Map<String,AuthorizeNetClient.CreateTransactionRequest>();
        this.policyVsResponse = new Map<String,AuthorizeNetClient.CreateTransactionResponse>();
        this.failedTransacation = new Map<Id,Object>();
    } 
    
    public Database.queryLocator start(Database.batchableContext BC){ 
        System.debug('Start Policy Renew Batch');
        Set<String> policyIdsQuery = new Set<String>();
        for(String policyIds : policyIdVsQuote.keyset()){
            System.debug('policyIds---'+policyIds);
            policyIdsQuery.add(policyIds);
        }
        System.debug('policyIdsQuery---'+policyIdsQuery);
        String query = 'SELECT id, Term__c, Term_days__c, Auto_renew__c, End_Date__c, Start_Date__c, Quote_c__c, Policy_Type_picklist__c,Contact__c,Auto_renew_card__c,Renew_Payment_Profile_Id__c,Auto_Renew_Confirmed__c,Updated_Quote_Json__c  from Policy__c WHERE ID IN: policyIdsQuery LIMIT 50000';
        System.debug('query'+query); 
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Policy__c> policyList){
        System.debug('getTransaction QueueableContext--');
         System.debug('policyList --'+policyList.size());
        Map<string, object> getTransaction = new Map<string, object>();
        Map<String,object> transactionDetails = new Map<String, object>();
        Map<String, Object> getTransactionDetails = new Map<String,Object>();
        
        if(policyList.size() > 0){
            for(Policy__c policy :policyList){
                
                List<String> quoteIdsList = new List<String>();
                String profileId = policy.Renew_Payment_Profile_Id__c;
                String contactId = policy.Contact__c;
                Quote__c quoteRecord = policyIdVsQuote.get(policy.Id);
                
                string policyId = policy.Id;
                string newQuoteID = quoteRecord.Id;
                quoteIdsList.add(quoteRecord.Id);
                
                if(quoteIdsList.size() > 0 && profileId != null){
                    transactionDetails.put('ip', '173.249.144.83');  // enter Current Ip...
                    transactionDetails.put('quoteIds' ,quoteIdsList);
                    transactionDetails.put('paymentProfileId',profileId);
                }
                
                System.debug('Details'+JSON.serialize(transactionDetails));
                getTransaction = PolicyAutoRenewCardHandler.createPaymentProfileTransaction(JSON.serialize(transactionDetails), contactId);
                System.debug('getTransaction--------'+getTransaction);
                policyIdsVsTransaction.put(policy.Id, getTransaction.get('status'));
                
                Object detailsObject = getTransaction.get('transcationDetails');
                Map<String, Object> details = (Map<String, Object>)detailsObject;
                if(getTransaction.get('status') == 'success'){
                    AuthorizeNetClient.CreateTransactionRequest request = (AuthorizeNetClient.CreateTransactionRequest)details.get('policyVsRequest');
                    AuthorizeNetClient.CreateTransactionResponse response = (AuthorizeNetClient.CreateTransactionResponse)details.get('policyVsResponse');
                    policyVsRequest.put(policy.Id,request);
                    policyVsResponse.put(policy.Id,response);
                }else{
                    failedTransacation.put(policy.Id, getTransaction.get('status'));
                    policyIdVsQuote.remove(policy.Id);
                    policyIdsVsTransaction.remove(policy.Id);
                }
                
            }
        }
    }
    
    public void finish (Database.BatchableContext Bc){
        System.debug('Finish PolicyAutoRenewGetTransaction---');
        System.debug('policyIdVsQuote--'+policyIdVsQuote);
        System.debug('policyIdsVsTransaction--'+policyIdsVsTransaction);
        
        if(policyVsRequest.size() > 0 && policyVsResponse.size() > 0){
            PolicyAutoRenewCardHandler.saveTransactionRecord(policyIdVsQuote, policyVsRequest, policyVsResponse, policyIdsVsTransaction);
        }
        
        System.debug('failedTransacation---'+failedTransacation);
        if(failedTransacation.size() > 0){
            PolicyAutoRenewCreateCase.createCase(failedTransacation);
        }
        
    }
    
}