force-app/main/default/objects/Policy__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Liability_picklist__c.field-meta.xml
<CustomField>
    <fullName>Liability_picklist__c</fullName>
    <label>Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Liability</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Medical_Payment__c.field-meta.xml
<CustomField>
    <fullName>Medical_Payment__c</fullName>
    <formula>Quote_c__r.Medical_Payment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Medical Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Medical_picklist__c.field-meta.xml
<CustomField>
    <fullName>Medical_picklist__c</fullName>
    <label>Medical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Medical</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Limited</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Max</fullName>
            </value>
            <value>
                <fullName>LiabilityTheft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automobile</fullName>
            </value>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Motorcycle/Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Northbound</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Quote_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote (c)</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Term_days__c.field-meta.xml
<CustomField>
    <fullName>Term_days__c</fullName>
    <label>Term_Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Underwriter__c</fullName>
    <label>Underwriter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chubb</fullName>
            </value>
            <value>
                <fullName>Mapfre</fullName>
            </value>
            <value>
                <fullName>Qualitas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter_picklist__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_picklist__c</fullName>
    <label>Underwriter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chubb</fullName>
            </value>
            <value>
                <fullName>Mapfre</fullName>
            </value>
            <value>
                <fullName>Qualitas</fullName>
            </value>
            <value>
                <fullName>GNP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Vehicle_type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_type__c</fullName>
    <label>Vehicle_Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Vehicle_Value__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Value__c</fullName>
    <formula>Vehicle_Policy__r.Value__c</formula>
    <label>Vehicle Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Limited</fullName>
            </value>
            <value>
                <fullName>Max</fullName>
            </value>
            <value>
                <fullName>LiabilityTheft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Driver_Age__c.field-meta.xml
<CustomField>
    <fullName>Driver_Age__c</fullName>
    <label>Driver Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/End_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>End_Date_for_Coverage__c</fullName>
    <label>End Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Is_there_a_driver_under_21__c.field-meta.xml
<CustomField>
    <fullName>Is_there_a_driver_under_21__c</fullName>
    <label>Is there a driver under 21</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
            <value>
                <fullName>true</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Liability</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Medical</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Medical_Payment__c.field-meta.xml
<CustomField>
    <fullName>Medical_Payment__c</fullName>
    <label>Medical Payment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Start_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_for_Coverage__c</fullName>
    <label>Start Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>90 Day</fullName>
            </value>
            <value>
                <fullName>Semi-Annual(Half a Year)</fullName>
            </value>
            <value>
                <fullName>Annual(One Year)</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Term_Days__c.field-meta.xml
<CustomField>
    <fullName>Term_Days__c</fullName>
    <label>Term Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Territory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Policy_Type_picklist__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Vehicle_Value__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Value__c</fullName>
    <label>Vehicle Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PopulatePayementDetailTest.cls
@isTest
public class PopulatePayementDetailTest {
	@isTest
    static void postiovemethod(){
        TriggerSwitch__c customset = new TriggerSwitch__c();
        customset.Name = 'PolicyTrigger';
        customset.Active__c = false;
        insert customset;
        lead ldObj = new lead();
        ldObj.company='abc';
        ldObj.email='ssharma'+String.valueOf(System.today())+'@gmail.com';
        ldObj.lastname='TestlastName';
        ldObj.status='New';  
        insert ldObj; 
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        insert acObj;
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
         List<Discount__c> discountList = new List<Discount__c>();
            for(Integer i=0 ; i < 4; i++){
                Discount__c discountObj = new Discount__c();
                if(i == 0){
                  discountObj.No_of_Days__c = 28;  
                }else if(i == 1){
                   discountObj.No_of_Days__c = 90; 
                }else if(i == 2){
                    discountObj.No_of_Days__c = 180; 
                }else{
                    discountObj.No_of_Days__c = 365; 
                }
                
                discountObj.Daily_Discount__c  = 0;
                discountList.add(discountObj);
            }
            
            insert discountList;
        
        Rate_Table__c ratesTable = new Rate_Table__c();
        ratesTable.Risk_1_Physical_Damages__c = 1.2087;
        ratesTable.Risk_2_Total_Theft__c = 0.5610;
        ratesTable.Underwriter__c = 'Chubb';
        ratesTable.type__c = 'Automobile';
        ratesTable.High_Value__c = 10000;
        ratesTable.Low_Value__c = 10000;
        ratesTable.Semi_Annual_Rate__c = 67;
        ratesTable.Semi_Annual_Total_Theft__c = 45;
        ratesTable.Annual_Rate__c = 89;
        ratesTable.Annual_Total_Theft__c = 35;
        insert ratesTable;
        
        Quote__c quoteRecord = new Quote__c();
        quoteRecord.Start_Date_for_Coverage__c= system.today();
        quoteRecord.End_Date_for_Coverage__c= system.today()+28;
        quoteRecord.Driver_Age__c = 80;
        quoteRecord.Lead__c = ldObj.Id;
        quoteRecord.contact__c = conObj.Id;
        quoteRecord.Account__c = acObj.Id;
        quoteRecord.Underwriter__c ='Chubb';
        quoteRecord.Coverage__c='Complete';
        quoteRecord.Territory__c='  Full';
        quoteRecord.Term__c='Daily';
        quoteRecord.Policy_Type_picklist__c='Automobile';
        quoteRecord.Vehicle_Type__c = 'Automobile';
        quoteRecord.Medical__c='20,000/100,000';
        quoteRecord.Liability__c='300,000'; 
        quoteRecord.Medical_Payment__c = 0;
        quoteRecord.Date_of_Birth__c = date.newinstance(1950,10,12);
        quoteRecord.Is_there_a_driver_under_21__c = 'Yes';
        quoteRecord.Vehicle_Value__c = 20000;
        insert quoteRecord;
        
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy';
        policyrecord.Quote_c__c = quoteRecord.Id;
        policyrecord.contact__c = conObj.id;
        policyrecord.Policy_Type_picklist__c = 'Automobile';
        policyrecord.Liability_picklist__c = '300,000';
        policyrecord.Medical_picklist__c = '5,000/25,000';
        policyrecord.Underwriter_picklist__c = 'Chubb';
        policyrecord.Package__c = 'Liability';
        policyrecord.Term_days__c = 28;
        
        insert policyrecord;
        
        Towed_Unit__c towed= new Towed_Unit__c();
        towed.Street_Legal__c='No';
        towed.Quote_c__c = quoteRecord.Id;
        towed.Account__c = acObj.Id;
        towed.Days_in_Tow__c = 180;
        towed.Policy__c =policyrecord.Id;
        
        insert towed;
        
        
        Quote_Towed_Unit__c quoteTowedUnit = new Quote_Towed_Unit__c();
        quoteTowedUnit.Towed_Unit__c = towed.Id;
        quoteTowedUnit.Quote_c__c = quoteRecord.Id;
        
        insert quoteTowedUnit;
        
        
        Test.startTest();
        PopulatePaymentDetail.calculateAndPopulateData();
        
        
        policyrecord.Term_days__c = 180;
        
        update policyrecord;
       // quoteRecord.End_Date_for_Coverage__c= system.today()+180;
       // update quoteRecord;
        PopulatePaymentDetail.calculateAndPopulateData();
        
        policyrecord.Term_days__c = 365;
        
        update policyrecord;
        
        quoteRecord.End_Date_for_Coverage__c= system.today()+365;
        update quoteRecord;
        PopulatePaymentDetail.calculateAndPopulateData();
       
        
        Test.stopTest(); 
        
    }
    
     @isTest
    static void postiovemethod11(){
          TriggerSwitch__c customset = new TriggerSwitch__c();
        customset.Name = 'PolicyTrigger';
        customset.Active__c = false;
        insert customset;
        lead ldObj = new lead();
        ldObj.company='abc';
        ldObj.email='ssharma'+String.valueOf(System.today())+'@gmail.com';
        ldObj.lastname='TestlastName';
        ldObj.status='New';  
        insert ldObj; 
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        insert acObj;
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
         List<Discount__c> discountList = new List<Discount__c>();
            for(Integer i=0 ; i < 4; i++){
                Discount__c discountObj = new Discount__c();
                if(i == 0){
                  discountObj.No_of_Days__c = 28;  
                }else if(i == 1){
                   discountObj.No_of_Days__c = 90; 
                }else if(i == 2){
                    discountObj.No_of_Days__c = 180; 
                }else{
                    discountObj.No_of_Days__c = 365; 
                }
                
                discountObj.Daily_Discount__c  = 0;
                discountList.add(discountObj);
            }
            
            insert discountList;
        
        Rate_Table__c ratesTable = new Rate_Table__c();
        ratesTable.Risk_1_Physical_Damages__c = 1.2087;
        ratesTable.Risk_2_Total_Theft__c = 0.5610;
        ratesTable.Underwriter__c = 'Chubb';
        ratesTable.type__c = 'Automobile';
        ratesTable.High_Value__c = 10000;
        ratesTable.Low_Value__c = 10000;
        ratesTable.Semi_Annual_Rate__c = 67;
        ratesTable.Semi_Annual_Total_Theft__c = 45;
        ratesTable.Annual_Rate__c = 89;
        ratesTable.Annual_Total_Theft__c = 35;
        insert ratesTable;
        Test.startTest();
        Quote__c quoteRecord = new Quote__c();
        quoteRecord.Start_Date_for_Coverage__c= system.today();
        quoteRecord.End_Date_for_Coverage__c= system.today()+180;
        quoteRecord.Driver_Age__c = 80;
        quoteRecord.Lead__c = ldObj.Id;
        quoteRecord.contact__c = conObj.Id;
        quoteRecord.Account__c = acObj.Id;
        quoteRecord.Underwriter__c ='Chubb';
        quoteRecord.Coverage__c='Complete';
        quoteRecord.Territory__c='  Full';
        quoteRecord.Term__c='Daily';
        quoteRecord.Policy_Type_picklist__c='Automobile';
        quoteRecord.Vehicle_Type__c = 'Automobile';
        quoteRecord.Medical__c='20,000/100,000';
        quoteRecord.Liability__c='300,000'; 
        quoteRecord.Medical_Payment__c = 0;
        quoteRecord.Date_of_Birth__c = date.newinstance(1950,10,12);
        quoteRecord.Is_there_a_driver_under_21__c = 'Yes';
        quoteRecord.Vehicle_Value__c = 20000;
        insert quoteRecord;
        
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy';
        policyrecord.Quote_c__c = quoteRecord.Id;
        policyrecord.contact__c = conObj.id;
        policyrecord.Policy_Type_picklist__c = 'Automobile';
        policyrecord.Liability_picklist__c = '300,000';
        policyrecord.Medical_picklist__c = '5,000/25,000';
        policyrecord.Underwriter_picklist__c = 'Chubb';
        policyrecord.Package__c = 'Liability';
        policyrecord.Term_days__c = 180;
        
        insert policyrecord;
        
        Towed_Unit__c towed= new Towed_Unit__c();
        towed.Street_Legal__c='No';
        towed.Quote_c__c = quoteRecord.Id;
        towed.Account__c = acObj.Id;
        towed.Days_in_Tow__c = 180;
        towed.Policy__c =policyrecord.Id;
        
        insert towed;
        
        
        Quote_Towed_Unit__c quoteTowedUnit = new Quote_Towed_Unit__c();
        quoteTowedUnit.Towed_Unit__c = towed.Id;
        quoteTowedUnit.Quote_c__c = quoteRecord.Id;
        
        insert quoteTowedUnit;
        
        
        
        PopulatePaymentDetail.calculateAndPopulateData();
        
        quoteRecord.Is_there_a_driver_under_21__c = 'No';
        update quoteRecord;
        
        PopulatePaymentDetail.calculateAndPopulateData();        
        Test.stopTest();
    }
    
  @isTest
    static void postiovemethod12(){
          TriggerSwitch__c customset = new TriggerSwitch__c();
        customset.Name = 'PolicyTrigger';
        customset.Active__c = false;
        insert customset;
        lead ldObj = new lead();
        ldObj.company='abc';
        ldObj.email='ssharma'+String.valueOf(System.today())+'@gmail.com';
        ldObj.lastname='TestlastName';
        ldObj.status='New';  
        insert ldObj; 
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        insert acObj;
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
         List<Discount__c> discountList = new List<Discount__c>();
            for(Integer i=0 ; i < 4; i++){
                Discount__c discountObj = new Discount__c();
                if(i == 0){
                  discountObj.No_of_Days__c = 28;  
                }else if(i == 1){
                   discountObj.No_of_Days__c = 90; 
                }else if(i == 2){
                    discountObj.No_of_Days__c = 180; 
                }else{
                    discountObj.No_of_Days__c = 365; 
                }
                
                discountObj.Daily_Discount__c  = 00;
                discountList.add(discountObj);
            }
            
            insert discountList;
        
        Rate_Table__c ratesTable = new Rate_Table__c();
        ratesTable.Risk_1_Physical_Damages__c = 85.2087;
        ratesTable.Risk_2_Total_Theft__c = 15.5610;
        ratesTable.Underwriter__c = 'Chubb';
        ratesTable.type__c = 'Automobile';
        ratesTable.High_Value__c = 200000;
        ratesTable.Low_Value__c = 10000;
        ratesTable.Semi_Annual_Rate__c = 167;
        ratesTable.Semi_Annual_Total_Theft__c = 545;
        ratesTable.Annual_Rate__c = 89;
        ratesTable.Annual_Total_Theft__c = 35;
        insert ratesTable;
       Test.startTest(); 
        Quote__c quoteRecord = new Quote__c();
        quoteRecord.Start_Date_for_Coverage__c= system.today();
        quoteRecord.End_Date_for_Coverage__c= system.today()+365;
        quoteRecord.Driver_Age__c = 80;
        quoteRecord.Lead__c = ldObj.Id;
        quoteRecord.contact__c = conObj.Id;
        quoteRecord.Account__c = acObj.Id;
        quoteRecord.Underwriter__c ='Chubb';
        quoteRecord.Coverage__c='Complete';
        quoteRecord.Territory__c='  Full';
        quoteRecord.Term__c='Daily';
        quoteRecord.Policy_Type_picklist__c='Automobile';
        quoteRecord.Vehicle_Type__c = 'Automobile';
        quoteRecord.Medical__c='20,000/100,000';
        quoteRecord.Liability__c='300,000'; 
        quoteRecord.Medical_Payment__c = 0;
        quoteRecord.Date_of_Birth__c = date.newinstance(1950,10,12);
        quoteRecord.Is_there_a_driver_under_21__c = 'Yes';
        quoteRecord.Vehicle_Value__c = 20000;
        insert quoteRecord;
        
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy';
        policyrecord.Quote_c__c = quoteRecord.Id;
        policyrecord.contact__c = conObj.id;
        policyrecord.Policy_Type_picklist__c = 'Automobile';
        policyrecord.Liability_picklist__c = '300,000';
        policyrecord.Medical_picklist__c = '5,000/25,000';
        policyrecord.Underwriter_picklist__c = 'Chubb';
        policyrecord.Package__c = 'Liability';
        policyrecord.Term_days__c = 365;
        
        insert policyrecord;
        
        Towed_Unit__c towed= new Towed_Unit__c();
        towed.Street_Legal__c='No';
        towed.Quote_c__c = quoteRecord.Id;
        towed.Account__c = acObj.Id;
        towed.Days_in_Tow__c = 180;
        towed.Policy__c =policyrecord.Id;
        
        insert towed;
        
        
        Quote_Towed_Unit__c quoteTowedUnit = new Quote_Towed_Unit__c();
        quoteTowedUnit.Towed_Unit__c = towed.Id;
        quoteTowedUnit.Quote_c__c = quoteRecord.Id;
        
        insert quoteTowedUnit;
        
        
        
        PopulatePaymentDetail.calculateAndPopulateData();
        
        quoteRecord.Is_there_a_driver_under_21__c = 'No';
        update quoteRecord;
        
        PopulatePaymentDetail.calculateAndPopulateData();        
        Test.stopTest();
    } 
    @isTest
    static void postiovemethod0(){
        TriggerSwitch__c customset = new TriggerSwitch__c();
        customset.Name = 'PolicyTrigger';
        customset.Active__c = false;
        insert customset;
        lead ldObj = new lead();
        ldObj.company='abc';
        ldObj.email='ssharma'+String.valueOf(System.today())+'@gmail.com';
        ldObj.lastname='TestlastName';
        ldObj.status='New';  
        insert ldObj; 
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        insert acObj;
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
         List<Discount__c> discountList = new List<Discount__c>();
            for(Integer i=0 ; i < 4; i++){
                Discount__c discountObj = new Discount__c();
                if(i == 0){
                  discountObj.No_of_Days__c = 28;  
                }else if(i == 1){
                   discountObj.No_of_Days__c = 90; 
                }else if(i == 2){
                    discountObj.No_of_Days__c = 180; 
                }else{
                    discountObj.No_of_Days__c = 365; 
                }
                
                discountObj.Daily_Discount__c  = 0;
                discountList.add(discountObj);
            }
            
            insert discountList;
        
        Rate_Table__c ratesTable = new Rate_Table__c();
        ratesTable.Risk_1_Physical_Damages__c = 1.2087;
        ratesTable.Risk_2_Total_Theft__c = 0.5610;
        ratesTable.Underwriter__c = 'Chubb';
        ratesTable.type__c = 'Automobile';
        ratesTable.High_Value__c = 10000;
        ratesTable.Low_Value__c = 10000;
        ratesTable.Semi_Annual_Rate__c = 67;
        ratesTable.Semi_Annual_Total_Theft__c = 45;
        ratesTable.Annual_Rate__c = 89;
        ratesTable.Annual_Total_Theft__c = 35;
        insert ratesTable;
        
        Quote__c quoteRecord = new Quote__c();
        quoteRecord.Start_Date_for_Coverage__c= system.today();
        quoteRecord.End_Date_for_Coverage__c= system.today()+28;
        quoteRecord.Driver_Age__c = 80;
        quoteRecord.Lead__c = ldObj.Id;
        quoteRecord.contact__c = conObj.Id;
        quoteRecord.Account__c = acObj.Id;
        quoteRecord.Underwriter__c ='Chubb';
        quoteRecord.Coverage__c='Complete';
        quoteRecord.Territory__c='  Full';
        quoteRecord.Term__c='Daily';
        quoteRecord.Policy_Type_picklist__c='Automobile';
        quoteRecord.Vehicle_Type__c = 'Automobile';
        quoteRecord.Medical__c='20,000/100,000';
        quoteRecord.Liability__c='300,000'; 
        quoteRecord.Medical_Payment__c = 0;
        quoteRecord.Date_of_Birth__c = date.newinstance(1950,10,12);
        quoteRecord.Is_there_a_driver_under_21__c = 'Yes';
        quoteRecord.Vehicle_Value__c = 20000;
        insert quoteRecord;
        
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy';
        policyrecord.Quote_c__c = quoteRecord.Id;
        policyrecord.contact__c = conObj.id;
        policyrecord.Policy_Type_picklist__c = 'Automobile';
        policyrecord.Liability_picklist__c = '300,000';
        policyrecord.Medical_picklist__c = '5,000/25,000';
        policyrecord.Underwriter_picklist__c = 'Chubb';
        policyrecord.Package__c = 'Liability';
        policyrecord.Term_days__c = 28;
        
        insert policyrecord;
        
        Towed_Unit__c towed= new Towed_Unit__c();
        towed.Street_Legal__c='No';
        towed.Quote_c__c = quoteRecord.Id;
        towed.Account__c = acObj.Id;
        towed.Days_in_Tow__c = 180;
        towed.Policy__c =policyrecord.Id;
        
        insert towed;
        
        
        Quote_Towed_Unit__c quoteTowedUnit = new Quote_Towed_Unit__c();
        quoteTowedUnit.Towed_Unit__c = towed.Id;
        quoteTowedUnit.Quote_c__c = quoteRecord.Id;
        
        insert quoteTowedUnit;
        
        
        Test.startTest();
        PopulatePaymentDetail.calculateAndPopulateData();
       
        
        Test.stopTest(); 
        
    }
    
     @isTest
    static void postiovemethod111(){
          TriggerSwitch__c customset = new TriggerSwitch__c();
        customset.Name = 'PolicyTrigger';
        customset.Active__c = false;
        insert customset;
        lead ldObj = new lead();
        ldObj.company='abc';
        ldObj.email='ssharma'+String.valueOf(System.today())+'@gmail.com';
        ldObj.lastname='TestlastName';
        ldObj.status='New';  
        insert ldObj; 
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        insert acObj;
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
         List<Discount__c> discountList = new List<Discount__c>();
            for(Integer i=0 ; i < 4; i++){
                Discount__c discountObj = new Discount__c();
                if(i == 0){
                  discountObj.No_of_Days__c = 28;  
                }else if(i == 1){
                   discountObj.No_of_Days__c = 90; 
                }else if(i == 2){
                    discountObj.No_of_Days__c = 180; 
                }else{
                    discountObj.No_of_Days__c = 365; 
                }
                
                discountObj.Daily_Discount__c  = 0;
                discountList.add(discountObj);
            }
            
            insert discountList;
        
        Rate_Table__c ratesTable = new Rate_Table__c();
        ratesTable.Risk_1_Physical_Damages__c = 1.2087;
        ratesTable.Risk_2_Total_Theft__c = 0.5610;
        ratesTable.Underwriter__c = 'Chubb';
        ratesTable.type__c = 'Automobile';
        ratesTable.High_Value__c = 10000;
        ratesTable.Low_Value__c = 10000;
        ratesTable.Semi_Annual_Rate__c = 67;
        ratesTable.Semi_Annual_Total_Theft__c = 45;
        ratesTable.Annual_Rate__c = 89;
        ratesTable.Annual_Total_Theft__c = 35;
        insert ratesTable;
        Test.startTest();
        Quote__c quoteRecord = new Quote__c();
        quoteRecord.Start_Date_for_Coverage__c= system.today();
        quoteRecord.End_Date_for_Coverage__c= system.today()+180;
        quoteRecord.Driver_Age__c = 80;
        quoteRecord.Lead__c = ldObj.Id;
        quoteRecord.contact__c = conObj.Id;
        quoteRecord.Account__c = acObj.Id;
        quoteRecord.Underwriter__c ='Chubb';
        quoteRecord.Coverage__c='Complete';
        quoteRecord.Territory__c='  Full';
        quoteRecord.Term__c='Daily';
        quoteRecord.Policy_Type_picklist__c='Automobile';
        quoteRecord.Vehicle_Type__c = 'Automobile';
        quoteRecord.Medical__c='20,000/100,000';
        quoteRecord.Liability__c='300,000'; 
        quoteRecord.Medical_Payment__c = 0;
        quoteRecord.Date_of_Birth__c = date.newinstance(1950,10,12);
        quoteRecord.Is_there_a_driver_under_21__c = 'No';
        quoteRecord.Vehicle_Value__c = 20000;
        insert quoteRecord;
        
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy';
        policyrecord.Quote_c__c = quoteRecord.Id;
        policyrecord.contact__c = conObj.id;
        policyrecord.Policy_Type_picklist__c = 'Automobile';
        policyrecord.Liability_picklist__c = '300,000';
        policyrecord.Medical_picklist__c = '5,000/25,000';
        policyrecord.Underwriter_picklist__c = 'Chubb';
        policyrecord.Package__c = 'Liability';
        policyrecord.Term_days__c = 180;
        
        insert policyrecord;
        
        Towed_Unit__c towed= new Towed_Unit__c();
        towed.Street_Legal__c='No';
        towed.Quote_c__c = quoteRecord.Id;
        towed.Account__c = acObj.Id;
        towed.Days_in_Tow__c = 180;
        towed.Policy__c =policyrecord.Id;
        
        insert towed;
        
        
        Quote_Towed_Unit__c quoteTowedUnit = new Quote_Towed_Unit__c();
        quoteTowedUnit.Towed_Unit__c = towed.Id;
        quoteTowedUnit.Quote_c__c = quoteRecord.Id;
        
        insert quoteTowedUnit;
        
        
        
        PopulatePaymentDetail.calculateAndPopulateData();
        
        
        PopulatePaymentDetail.calculateAndPopulateData();        
        Test.stopTest();
    }
    
  @isTest
    static void postiovemethod121(){
          TriggerSwitch__c customset = new TriggerSwitch__c();
        customset.Name = 'PolicyTrigger';
        customset.Active__c = false;
        insert customset;
        lead ldObj = new lead();
        ldObj.company='abc';
        ldObj.email='ssharma'+String.valueOf(System.today())+'@gmail.com';
        ldObj.lastname='TestlastName';
        ldObj.status='New';  
        insert ldObj; 
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        insert acObj;
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
         List<Discount__c> discountList = new List<Discount__c>();
            for(Integer i=0 ; i < 4; i++){
                Discount__c discountObj = new Discount__c();
                if(i == 0){
                  discountObj.No_of_Days__c = 28;  
                }else if(i == 1){
                   discountObj.No_of_Days__c = 90; 
                }else if(i == 2){
                    discountObj.No_of_Days__c = 180; 
                }else{
                    discountObj.No_of_Days__c = 365; 
                }
                
                discountObj.Daily_Discount__c  = 00;
                discountList.add(discountObj);
            }
            
            insert discountList;
        
        Rate_Table__c ratesTable = new Rate_Table__c();
        ratesTable.Risk_1_Physical_Damages__c = 85.2087;
        ratesTable.Risk_2_Total_Theft__c = 15.5610;
        ratesTable.Underwriter__c = 'Chubb';
        ratesTable.type__c = 'Automobile';
        ratesTable.High_Value__c = 200000;
        ratesTable.Low_Value__c = 10000;
        ratesTable.Semi_Annual_Rate__c = 167;
        ratesTable.Semi_Annual_Total_Theft__c = 545;
        ratesTable.Annual_Rate__c = 89;
        ratesTable.Annual_Total_Theft__c = 35;
        insert ratesTable;
       Test.startTest(); 
        Quote__c quoteRecord = new Quote__c();
        quoteRecord.Start_Date_for_Coverage__c= system.today();
        quoteRecord.End_Date_for_Coverage__c= system.today()+365;
        quoteRecord.Driver_Age__c = 80;
        quoteRecord.Lead__c = ldObj.Id;
        quoteRecord.contact__c = conObj.Id;
        quoteRecord.Account__c = acObj.Id;
        quoteRecord.Underwriter__c ='Chubb';
        quoteRecord.Coverage__c='Complete';
        quoteRecord.Territory__c='  Full';
        quoteRecord.Term__c='Daily';
        quoteRecord.Policy_Type_picklist__c='Automobile';
        quoteRecord.Vehicle_Type__c = 'Automobile';
        quoteRecord.Medical__c='20,000/100,000';
        quoteRecord.Liability__c='300,000'; 
        quoteRecord.Medical_Payment__c = 0;
        quoteRecord.Date_of_Birth__c = date.newinstance(1950,10,12);
        quoteRecord.Is_there_a_driver_under_21__c = 'No';
        quoteRecord.Vehicle_Value__c = 20000;
        insert quoteRecord;
        
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy';
        policyrecord.Quote_c__c = quoteRecord.Id;
        policyrecord.contact__c = conObj.id;
        policyrecord.Policy_Type_picklist__c = 'Automobile';
        policyrecord.Liability_picklist__c = '300,000';
        policyrecord.Medical_picklist__c = '5,000/25,000';
        policyrecord.Underwriter_picklist__c = 'Chubb';
        policyrecord.Package__c = 'Liability';
        policyrecord.Term_days__c = 365;
        
        insert policyrecord;
        
        Towed_Unit__c towed= new Towed_Unit__c();
        towed.Street_Legal__c='No';
        towed.Quote_c__c = quoteRecord.Id;
        towed.Account__c = acObj.Id;
        towed.Days_in_Tow__c = 180;
        towed.Policy__c =policyrecord.Id;
        
        insert towed;
        
        
        Quote_Towed_Unit__c quoteTowedUnit = new Quote_Towed_Unit__c();
        quoteTowedUnit.Towed_Unit__c = towed.Id;
        quoteTowedUnit.Quote_c__c = quoteRecord.Id;
        
        insert quoteTowedUnit;
        
        
        
        PopulatePaymentDetail.calculateAndPopulateData();
        
        
        PopulatePaymentDetail.calculateAndPopulateData();        
        Test.stopTest();
    } 
    
    
    @isTest
    static void postiovemethod20(){
        TriggerSwitch__c customset = new TriggerSwitch__c();
        customset.Name = 'PolicyTrigger';
        customset.Active__c = false;
        insert customset;
        lead ldObj = new lead();
        ldObj.company='abc';
        ldObj.email='ssharma'+String.valueOf(System.today())+'@gmail.com';
        ldObj.lastname='TestlastName';
        ldObj.status='New';  
        insert ldObj; 
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        insert acObj;
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
        
        Rate_Table__c ratesTable = new Rate_Table__c();
        ratesTable.Risk_1_Physical_Damages__c = 16;
        ratesTable.Risk_2_Total_Theft__c = 25;
        ratesTable.Underwriter__c = 'Chubb';
        ratesTable.type__c = 'Automobile';
        ratesTable.High_Value__c = 10000;
        ratesTable.Low_Value__c = 10000;
        ratesTable.Semi_Annual_Rate__c = 125;
        ratesTable.Semi_Annual_Total_Theft__c = 105;
        ratesTable.Annual_Rate__c = 2;
        ratesTable.Annual_Total_Theft__c = 5;
        insert ratesTable;
        
         
         List<Discount__c> discountList = new List<Discount__c>();
            for(Integer i=0 ; i < 4; i++){
                Discount__c discountObj = new Discount__c();
                if(i == 0){
                  discountObj.No_of_Days__c = 28;  
                }else if(i == 1){
                   discountObj.No_of_Days__c = 90; 
                }else if(i == 2){
                    discountObj.No_of_Days__c = 180; 
                }else{
                    discountObj.No_of_Days__c = 365; 
                }
                
                discountObj.Daily_Discount__c  = 0;
                discountList.add(discountObj);
            }
            
            insert discountList;
        
        
        
        Quote__c quoteRecord = new Quote__c();
        quoteRecord.Start_Date_for_Coverage__c= system.today();
        quoteRecord.End_Date_for_Coverage__c= system.today()+28;
        quoteRecord.Driver_Age__c = 80;
        quoteRecord.Lead__c = ldObj.Id;
        quoteRecord.contact__c = conObj.Id;
        quoteRecord.Account__c = acObj.Id;
        quoteRecord.Underwriter__c ='Chubb';
        quoteRecord.Coverage__c='Complete';
        quoteRecord.Territory__c='  Full';
        quoteRecord.Term__c='Daily';
        quoteRecord.Policy_Type_picklist__c='Automobile';
        quoteRecord.Vehicle_Type__c = 'RAutomobileV';
        quoteRecord.Medical__c='20,000/100,000';
        quoteRecord.Liability__c='300,000'; 
        quoteRecord.Medical_Payment__c = 0;
        quoteRecord.Date_of_Birth__c = date.newinstance(1950,10,12);
        quoteRecord.Is_there_a_driver_under_21__c = 'Yes';
        quoteRecord.Vehicle_Value__c = 20000; 
        insert quoteRecord;
        
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy';
        policyrecord.Quote_c__c = quoteRecord.Id;
        policyrecord.contact__c = conObj.id;
        policyrecord.Policy_Type_picklist__c = 'Automobile';
        policyrecord.Liability_picklist__c = '500,000';
        policyrecord.Medical_picklist__c = '10,000/50,000';
        policyrecord.Underwriter_picklist__c = 'Chubb';
        policyrecord.Package__c = 'Complete';
        policyrecord.Term_days__c = 28;
        
        insert policyrecord;
        
        Towed_Unit__c towed= new Towed_Unit__c();
        towed.Street_Legal__c='No';
        towed.Quote_c__c = quoteRecord.Id;
        towed.Account__c = acObj.Id;
        towed.Days_in_Tow__c = 180;
        towed.Policy__c =policyrecord.Id;
        
        insert towed;
        
        
        Quote_Towed_Unit__c quoteTowedUnit = new Quote_Towed_Unit__c();
        quoteTowedUnit.Towed_Unit__c = towed.Id;
        quoteTowedUnit.Quote_c__c = quoteRecord.Id;
        
        insert quoteTowedUnit;
        
        Test.startTest();
        PopulatePaymentDetail.calculateAndPopulateData();
        
        
        Test.stopTest();
        
    }
    
    
    @isTest
    static void postiovemethod2(){
        TriggerSwitch__c customset = new TriggerSwitch__c();
        customset.Name = 'PolicyTrigger';
        customset.Active__c = false;
        insert customset;
        lead ldObj = new lead();
        ldObj.company='abc';
        ldObj.email='ssharma'+String.valueOf(System.today())+'@gmail.com';
        ldObj.lastname='TestlastName';
        ldObj.status='New';  
        insert ldObj; 
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        insert acObj;
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
        
        Rate_Table__c ratesTable = new Rate_Table__c();
        ratesTable.Risk_1_Physical_Damages__c = 1.2087;
        ratesTable.Risk_2_Total_Theft__c = 0.5610;
        ratesTable.Underwriter__c = 'Chubb';
        ratesTable.type__c = 'Automobile';
        ratesTable.High_Value__c = 10000;
        ratesTable.Low_Value__c = 10000;
        ratesTable.Semi_Annual_Rate__c = 67;
        ratesTable.Semi_Annual_Total_Theft__c = 95;
        ratesTable.Annual_Rate__c = 89;
        ratesTable.Annual_Total_Theft__c = 105;
        insert ratesTable;
        
         
         List<Discount__c> discountList = new List<Discount__c>();
            for(Integer i=0 ; i < 4; i++){
                Discount__c discountObj = new Discount__c();
                if(i == 0){
                  discountObj.No_of_Days__c = 28;  
                }else if(i == 1){
                   discountObj.No_of_Days__c = 90; 
                }else if(i == 2){
                    discountObj.No_of_Days__c = 180; 
                }else{
                    discountObj.No_of_Days__c = 365; 
                }
                
                discountObj.Daily_Discount__c  = 0;
                discountList.add(discountObj);
            }
            
            insert discountList;
        
        
        
        Quote__c quoteRecord = new Quote__c();
        quoteRecord.Start_Date_for_Coverage__c= system.today();
        quoteRecord.End_Date_for_Coverage__c= system.today()+365;
        quoteRecord.Driver_Age__c = 80;
        quoteRecord.Lead__c = ldObj.Id;
        quoteRecord.contact__c = conObj.Id;
        quoteRecord.Account__c = acObj.Id;
        quoteRecord.Underwriter__c ='Chubb';
        quoteRecord.Coverage__c='Complete';
        quoteRecord.Territory__c='  Full';
        quoteRecord.Term__c='Daily';
        quoteRecord.Policy_Type_picklist__c='Automobile';
        quoteRecord.Vehicle_Type__c = 'Automobile';
        quoteRecord.Medical__c='20,000/100,000';
        quoteRecord.Liability__c='300,000'; 
        quoteRecord.Medical_Payment__c = 0;
        quoteRecord.Date_of_Birth__c = date.newinstance(1950,10,12);
        quoteRecord.Is_there_a_driver_under_21__c = 'Yes';
        quoteRecord.Vehicle_Value__c = 200000; 
        insert quoteRecord;
        
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy';
        policyrecord.Quote_c__c = quoteRecord.Id;
        policyrecord.contact__c = conObj.id;
        policyrecord.Policy_Type_picklist__c = 'Automobile';
        policyrecord.Liability_picklist__c = '500,000';
        policyrecord.Medical_picklist__c = '10,000/50,000';
        policyrecord.Underwriter_picklist__c = 'Chubb';
        policyrecord.Package__c = 'Complete';
        policyrecord.Term_days__c = 365;
        
        insert policyrecord;
        
        Towed_Unit__c towed= new Towed_Unit__c();
        towed.Street_Legal__c='No';
        towed.Quote_c__c = quoteRecord.Id;
        towed.Account__c = acObj.Id;
        towed.Days_in_Tow__c = 180;
        towed.Policy__c =policyrecord.Id;
        
        insert towed;
        
        
        Quote_Towed_Unit__c quoteTowedUnit = new Quote_Towed_Unit__c();
        quoteTowedUnit.Towed_Unit__c = towed.Id;
        quoteTowedUnit.Quote_c__c = quoteRecord.Id;
        
        insert quoteTowedUnit;
        
        Test.startTest();
        PopulatePaymentDetail.calculateAndPopulateData();
        
        
        Test.stopTest();
        
    }
    
    @isTest
    static void postiovemethod21(){
        TriggerSwitch__c customset = new TriggerSwitch__c();
        customset.Name = 'PolicyTrigger';
        customset.Active__c = false;
        insert customset;
        lead ldObj = new lead();
        ldObj.company='abc';
        ldObj.email='ssharma'+String.valueOf(System.today())+'@gmail.com';
        ldObj.lastname='TestlastName';
        ldObj.status='New';  
        insert ldObj; 
        Account acObj=new account();
        acObj.name='testaccount';
        acObj.annualrevenue=2000;
        insert acObj;
        contact conObj =new contact();
        conObj.lastname='con';
        conObj.accountid=acObj.id;
        conObj.email='abc@gmail.com';
        insert conObj;
        
        
        Rate_Table__c ratesTable = new Rate_Table__c();
        ratesTable.Risk_1_Physical_Damages__c = 1.2087;
        ratesTable.Risk_2_Total_Theft__c = 0.5610;
        ratesTable.Underwriter__c = 'Chubb';
        ratesTable.type__c = 'Automobile';
        ratesTable.High_Value__c = 10000;
        ratesTable.Low_Value__c = 800000;
        ratesTable.Semi_Annual_Rate__c = 67;
        ratesTable.Semi_Annual_Total_Theft__c = 95;
        ratesTable.Annual_Rate__c = 89;
        ratesTable.Annual_Total_Theft__c = 105;
        insert ratesTable;
        
         
         List<Discount__c> discountList = new List<Discount__c>();
            for(Integer i=0 ; i < 4; i++){
                Discount__c discountObj = new Discount__c();
                if(i == 0){
                  discountObj.No_of_Days__c = 28;  
                }else if(i == 1){
                   discountObj.No_of_Days__c = 90; 
                }else if(i == 2){
                    discountObj.No_of_Days__c = 180; 
                }else{
                    discountObj.No_of_Days__c = 365; 
                }
                
                discountObj.Daily_Discount__c  = 0;
                discountList.add(discountObj);
            }
            
            insert discountList;
        
        
        
        Quote__c quoteRecord = new Quote__c();
        quoteRecord.Start_Date_for_Coverage__c= system.today();
        quoteRecord.End_Date_for_Coverage__c= system.today()+180;
        quoteRecord.Driver_Age__c = 80;
        quoteRecord.Lead__c = ldObj.Id;
        quoteRecord.contact__c = conObj.Id;
        quoteRecord.Account__c = acObj.Id;
        quoteRecord.Underwriter__c ='Chubb';
        quoteRecord.Coverage__c='Complete';
        quoteRecord.Territory__c='  Full';
        quoteRecord.Term__c='Daily';
        quoteRecord.Policy_Type_picklist__c='Automobile';
        quoteRecord.Vehicle_Type__c = 'Automobile';
        quoteRecord.Medical__c='20,000/100,000';
        quoteRecord.Liability__c='300,000'; 
        quoteRecord.Medical_Payment__c = 0;
        quoteRecord.Date_of_Birth__c = date.newinstance(1950,10,12);
        quoteRecord.Is_there_a_driver_under_21__c = 'Yes';
        quoteRecord.Vehicle_Value__c = 600000; 
        insert quoteRecord;
        
        Policy__c policyrecord = new policy__c();
        policyrecord.name='policy';
        policyrecord.Quote_c__c = quoteRecord.Id;
        policyrecord.contact__c = conObj.id;
        policyrecord.Policy_Type_picklist__c = 'Automobile';
        policyrecord.Liability_picklist__c = '500,000';
        policyrecord.Medical_picklist__c = '10,000/50,000';
        policyrecord.Underwriter_picklist__c = 'Chubb';
        policyrecord.Package__c = 'Complete';
        policyrecord.Term_days__c = 180;
        
        insert policyrecord;
        
        Towed_Unit__c towed= new Towed_Unit__c();
        towed.Street_Legal__c='No';
        towed.Quote_c__c = quoteRecord.Id;
        towed.Account__c = acObj.Id;
        towed.Days_in_Tow__c = 180;
        towed.Policy__c =policyrecord.Id;
        
        insert towed;
        
        
        Quote_Towed_Unit__c quoteTowedUnit = new Quote_Towed_Unit__c();
        quoteTowedUnit.Towed_Unit__c = towed.Id;
        quoteTowedUnit.Quote_c__c = quoteRecord.Id;
        
        insert quoteTowedUnit;
        
        Test.startTest();
        PopulatePaymentDetail.calculateAndPopulateData();
        
        Test.stopTest();
        
    }
}