force-app/main/default/objects/Policy__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automobile</fullName>
            </value>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Motorcycle/Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Northbound</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Quote_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote (c)</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Underwriter__c</fullName>
    <label>Underwriter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chubb</fullName>
            </value>
            <value>
                <fullName>Mapfre</fullName>
            </value>
            <value>
                <fullName>Qualitas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Vehicle_Policy__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle(Policy)</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Limited</fullName>
            </value>
            <value>
                <fullName>Max</fullName>
            </value>
            <value>
                <fullName>LiabilityTheft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Driver_Age__c.field-meta.xml
<CustomField>
    <fullName>Driver_Age__c</fullName>
    <label>Driver Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/End_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>End_Date_for_Coverage__c</fullName>
    <label>End Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Liability</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Medical</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Start_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_for_Coverage__c</fullName>
    <label>Start Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Quote_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote (c)</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quoted Vehicle</relationshipLabel>
    <relationshipName>Vehicle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Mex_Insurance_Calloututility_Test.cls
@isTest
private class Mex_Insurance_Calloututility_Test {
    public static testMethod void postiveTesting(){
        Test.setMock(HttpCalloutMock.class, new Mex_Insurance_Mock());
        Test.startTest();
            Mex_Insurance_Calloututility.sendEmail( new set<String>{'test'}, true);

            map<String,object> leadObjMap = new map<String,object>();
            leadObjMap.put('Email', 'test');
            Mex_Insurance_Calloututility.getLeadId( leadObjMap );

            Mex_Insurance_Calloututility.createLead_Record( leadObjMap );

        Test.stopTest();
    }

    public static testMethod void postiveSendEmailServiceTesting(){

        TriggerSwitch__c customset = new TriggerSwitch__c();
        customset.Name='PolicyTrigger';
        customset.Active__c=FALSE;
        insert customset;

        Account ac=new account();
        ac.name='testaccount';
        ac.annualrevenue=2000;
        insert ac;

        contact c=new contact();
        c.lastname='con';
        c.accountid=ac.id;
        c.email='abc@gmail.com';
        insert c;

        Quote__c quote = new quote__c();
        quote.Start_Date_for_Coverage__c=date.today();
        quote.End_Date_for_Coverage__c=date.today()+5;
        quote.Driver_Age__c = 80;
        quote.Underwriter__c ='Chubb';
        quote.Coverage__c='Complete';
        quote.Medical__c='2,000/10,000';
        quote.Liability__c='100,000'; 
        insert quote;
        
        vehicle__c vehicle = new vehicle__c();
        vehicle.Quote_c__c=quote.id;
        vehicle.Company_Name__c ='s';
        vehicle.Company_Address__c='abc';
        vehicle.type__c='car';
        vehicle.model__c='suv';
        vehicle.make__c='ford';
        vehicle.year__c='2020';     
        insert vehicle; 

        Policy__c policyrecord=new policy__c();
        policyrecord.name='policy';
        policyrecord.contact__c= c.id;
        policyrecord.Vehicle_Policy__c= vehicle.id;
        policyrecord.Policy_Type_picklist__c = 'Northbound';
        insert policyrecord;

        Test.startTest();
            map<String,object> leadObjMap = new map<String,object>();
            leadObjMap.put('policyIdset', new list<object>{ policyrecord.Id });
            leadObjMap.put('add_attachment', true);
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse(); 
            req.requestBody = Blob.valueOf(JSON.serialize(leadObjMap));           
            req.requestURI = '/services/apexrest/sendEmailService/*';
            req.httpMethod = 'POST';
            RestContext.request = req;
            RestContext.response= res;

            sendEmailService.sendEmail();

            ApexPages.currentPage().getParameters().put('id', policyrecord.id);
            Declaration_Page_Insurance_Controller declar = new Declaration_Page_Insurance_Controller();
            
        Test.stopTest();
    }
}