force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status_picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PolicyExpireBatch.cls
global class PolicyExpireBatch implements Database.Batchable<sObject>
{
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        Date todayDate = System.today();
        String query = 'SELECT Id, Name, Status_picklist__c, End_Date__c  FROM Policy__c Where Status_picklist__c = \'Active\' AND End_Date__c <=:todayDate LIMIT 50000';
        return Database.getQueryLocator(query);
    }
 
    global void execute(Database.BatchableContext BC, List<Policy__c> scope)
    {
        for (Policy__c each : scope) {
            each.Status_picklist__c = 'Expired';
        }

        update scope;
    }  

    global void finish(Database.BatchableContext BC)
    {
    }
}