force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AttachmentTriggerHandlerTest.cls
@isTest
public class AttachmentTriggerHandlerTest {
    @isTest static void updateAttachmentRecordTest() {
        // Switch off PolicyTrigger
        TriggerSwitch__c customset = new TriggerSwitch__c();
        customset.Name='PolicyTrigger';
        customset.Active__c=FALSE;
        insert customset;

        Quote__c qtRec = TestDataService.createQuote(true);
        Policy__c polRec = TestDataService.createPolicy(qtRec);

        Attachment newAtt = new Attachment();
        newAtt.Name = 'test attachment';
        newAtt.Body = Blob.valueOf('Test body data');
        newAtt.ParentId = polRec.Id;

        Test.startTest();
        insert newAtt;

        if (newAtt.Id != null) {
            newAtt.Description = 'Success';
            update newAtt;
        }
        Test.stopTest();
    }
}