force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automobile</fullName>
            </value>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Motorcycle/Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Northbound</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status_picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter_picklist__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_picklist__c</fullName>
    <label>Underwriter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chubb</fullName>
            </value>
            <value>
                <fullName>Mapfre</fullName>
            </value>
            <value>
                <fullName>Qualitas</fullName>
            </value>
            <value>
                <fullName>GNP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PolicyDocumentGeneratorTest.cls
@isTest
public class PolicyDocumentGeneratorTest {
    @isTest
    public static void generateGreenCardfromPolicyIdTest(){
        TriggerSwitch__c  triggerSwitchRecord = new TriggerSwitch__c();
        triggerSwitchRecord.Active__c = true;
        triggerSwitchRecord.Name = 'PolicyTrigger';
        insert triggerSwitchRecord;
        
        Policy__c plcy = new Policy__c();
        plcy.Name ='Test';
        plcy.Status_picklist__c='Active';
        plcy.End_Date__c= system.today(); 
        insert plcy;
        
        Policy__c policyDetail = [Select Id, Policy_Type_picklist__c from Policy__c Where Id =:plcy.Id LIMIT 1];
        String PolicyId = policyDetail.Id;
        Test.startTest();
        PolicyDocumentGenerator.generateGreenCardfromPolicyId(PolicyId);
        Test.stopTest();
    }
    @isTest
    public static void validateandGenerateQuotePDFTest(){
        TriggerSwitch__c  triggerSwitchRecord = new TriggerSwitch__c();
        triggerSwitchRecord.Active__c = false;
        triggerSwitchRecord.Name = 'PolicyTrigger';
        insert triggerSwitchRecord;
        
        Policy__c plcy = new Policy__c();
        plcy.Name ='Test';
        plcy.Status_picklist__c='Active';
        plcy.Policy_Type_picklist__c = 'Northbound';
        plcy.End_Date__c= system.today(); 
        insert plcy;
        
        Policy__c plcy1 = new Policy__c();
        plcy1.Name ='Test';
        plcy1.Status_picklist__c='Active';
        plcy1.Policy_Type_picklist__c = 'Driver License';
        plcy1.End_Date__c= system.today(); 
        insert plcy1;
        
        Policy__c plcy2 = new Policy__c();
        plcy2.Name ='Test';
        plcy2.Status_picklist__c='Active';
        plcy2.Policy_Type_picklist__c = 'Watercraft';
        plcy2.End_Date__c= system.today(); 
        insert plcy2;
        
        Policy__c plcy3 = new Policy__c();
        plcy3.Name ='Test';
        plcy3.Status_picklist__c='Active';
        plcy3.Policy_Type_picklist__c = 'Automobile';
        plcy3.Underwriter_picklist__c = 'Mapfre';
        plcy3.End_Date__c= system.today(); 
        insert plcy3;
        
         Policy__c plcy13 = new Policy__c();
        plcy13.Name ='Test';
        plcy13.Status_picklist__c='Active';
        plcy13.Policy_Type_picklist__c = 'Automobile';
        plcy13.Underwriter_picklist__c = 'Qualitas';
        plcy13.End_Date__c= system.today(); 
        insert plcy13;
        
        Policy__c plcy4 = new Policy__c();
        plcy4.Name ='Test';
        plcy4.Status_picklist__c='Active';
        plcy4.Policy_Type_picklist__c = 'Automobile';
        plcy4.Underwriter_picklist__c = 'Chubb';
        plcy4.End_Date__c= system.today(); 
        insert plcy4;
        
        Policy__c plcy5 = new Policy__c();
        plcy5.Name ='Test';
        plcy5.Status_picklist__c='Active';
        plcy5.Policy_Type_picklist__c = 'Motorcycle/Street Legal ATV';
        plcy5.Underwriter_picklist__c = 'Qualitas';
        plcy5.End_Date__c= system.today(); 
        insert plcy5;
        
        Policy__c plcy6 = new Policy__c();
        plcy6.Name ='Test';
        plcy6.Status_picklist__c='Active';
        plcy6.Policy_Type_picklist__c = 'Motorcycle/Street Legal ATV';
        plcy6.Underwriter_picklist__c = 'Chubb';
        plcy6.End_Date__c= system.today(); 
        insert plcy6;

        Policy__c plcy8 = new Policy__c();
        plcy8.Name ='Test';
        plcy8.Status_picklist__c='Active';
        plcy8.Policy_Type_picklist__c = 'Motorcycle/Street Legal ATV';
        plcy8.Underwriter_picklist__c = 'Mapfre';
        plcy8.End_Date__c= system.today(); 
        insert plcy8;
        
        Policy__c plcy7 = new Policy__c();
        plcy7.Name ='Test';
        plcy7.Status_picklist__c='Active';
        plcy7.Policy_Type_picklist__c = 'RV';
        plcy7.Underwriter_picklist__c = 'Chubb';
        plcy7.End_Date__c= system.today(); 
        insert plcy7;
        
        Policy__c plcy9 = new Policy__c();
        plcy9.Name ='Test';
        plcy9.Status_picklist__c='Active';
        plcy9.Policy_Type_picklist__c = 'RV';
        plcy7.Underwriter_picklist__c = 'Mapfre';
        plcy9.End_Date__c= system.today(); 
        insert plcy9;
        
        Policy__c plcy11 = new Policy__c();
        plcy11.Name ='Test';
        plcy11.Status_picklist__c='Active';
        plcy11.Policy_Type_picklist__c = 'RV';
        plcy7.Underwriter_picklist__c = 'Qualitas';
        plcy11.End_Date__c= system.today(); 
        insert plcy11;
        
        Policy__c policyDetail = [Select Id, Policy_Type_picklist__c from Policy__c Where Id =:plcy.Id LIMIT 1];
        String PolicyId = policyDetail.Id;
        Test.startTest();
        PolicyDocumentGenerator.validateandGenerateQuotePDF(plcy1.Id);
        PolicyDocumentGenerator.validateandGenerateQuotePDF(plcy2.Id);
        PolicyDocumentGenerator.validateandGenerateQuotePDF(plcy3.Id);
        PolicyDocumentGenerator.validateandGenerateQuotePDF(plcy4.Id);
        PolicyDocumentGenerator.validateandGenerateQuotePDF(plcy5.Id);
        PolicyDocumentGenerator.validateandGenerateQuotePDF(plcy6.Id);
        PolicyDocumentGenerator.validateandGenerateQuotePDF(plcy7.Id);
        PolicyDocumentGenerator.validateandGenerateQuotePDF(plcy8.Id);
        PolicyDocumentGenerator.validateandGenerateQuotePDF(plcy9.Id);
        PolicyDocumentGenerator.validateandGenerateQuotePDF(plcy11.Id);
        PolicyDocumentGenerator.validateandGenerateQuotePDF(plcy13.Id);
        Test.stopTest();
    }
    
}