force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Policy_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Policy_Expiration__c</fullName>
    <description>From the Policy object, should be updated whenever a new policy, policy edit or renewal is done. If the policy.expiration changes, automatically this field should also change.</description>
    <label>Policy Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Uninsured_Reason__c.field-meta.xml
<CustomField>
    <fullName>Uninsured_Reason__c</fullName>
    <label>Uninsured Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Will Renew Later</fullName>
            </value>
            <value>
                <fullName>Transferred Ownership</fullName>
            </value>
            <value>
                <fullName>Destroyed</fullName>
            </value>
            <value>
                <fullName>Stolen</fullName>
            </value>
            <value>
                <fullName>No Longer in Mexico</fullName>
            </value>
            <value>
                <fullName>Insured Elsewhere</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/vehicle_coverage_status__c.field-meta.xml
<CustomField>
    <fullName>vehicle_coverage_status__c</fullName>
    <label>Vehicle Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>insured</fullName>
            </value>
            <value>
                <fullName>insured-annual</fullName>
            </value>
            <value>
                <fullName>uninsured</fullName>
            </value>
            <value>
                <fullName>insured-renew</fullName>
            </value>
            <value>
                <fullName>insured-renew-annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vin__c.field-meta.xml
<CustomField>
    <fullName>Vin__c</fullName>
    <label>Vin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VehicleRenewalBatch.cls
public with sharing class VehicleRenewalBatch implements Database.Batchable<SObject>, Database.Stateful {

    private Date cutoffDate = Date.newInstance(2015, 1, 1);

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Vin__c, Policy__c, Policy_Expiration__c, vehicle_coverage_status__c, Uninsured_Reason__c ' +
                       'FROM Vehicle__c WHERE CreatedDate >= :cutoffDate ORDER BY Id';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        // Convertir la lista de SObject a Vehicle__c
        List<Vehicle__c> vehicles = (List<Vehicle__c>)scope;
        VehicleRenewalProcessor.processBatchOfVehicles(vehicles);
    }

    public void finish(Database.BatchableContext bc) {
        // Opcional: enviar correo, logs, etc.
    }
}