force-app/main/default/objects/Driver__c/fields/Account_Driver__c.field-meta.xml
<CustomField>
    <fullName>Account_Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <label>Address (Line 2)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Dob__c.field-meta.xml
<CustomField>
    <fullName>Dob__c</fullName>
    <label>DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Driver_Type__c.field-meta.xml
<CustomField>
    <fullName>Driver_Type__c</fullName>
    <label>Driver Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Co-Owner</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Owner &amp; Driver</fullName>
            </value>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State / Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Account_Policy__c.field-meta.xml
<CustomField>
    <fullName>Account_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Chubb_Policy_Number__c.field-meta.xml
<CustomField>
    <fullName>Chubb_Policy_Number__c</fullName>
    <label>Chubb Policy Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Range_Number__c.field-meta.xml
<CustomField>
    <fullName>Policy_Range_Number__c</fullName>
    <formula>RIGHT(LEFT(Chubb_Policy_Number__c,11),6)</formula>
    <label>Policy Range Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automobile</fullName>
            </value>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Motorcycle/Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Northbound</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Portal</fullName>
            </value>
            <value>
                <fullName>New Lead Flow</fullName>
            </value>
            <value>
                <fullName>MexInsur</fullName>
            </value>
            <value>
                <fullName>Agent App</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter_picklist__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_picklist__c</fullName>
    <label>Underwriter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chubb</fullName>
            </value>
            <value>
                <fullName>Mapfre</fullName>
            </value>
            <value>
                <fullName>Qualitas</fullName>
            </value>
            <value>
                <fullName>GNP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PolicyTriggerHandler.cls
/*
* Class Name : PolicyTriggerHandler
* Description : Manages all the updates on the policy and its related records on various events respectively.
* Created Date :
* Created By :
* Version : 1.1
* Modification Log :
* Name				Date			Version				Description
* Abhishek Sahay	6/9/2022		1.1					Validate and update the Chubb policy number.
*/
public  class PolicyTriggerHandler  
{
    
    /* public void OnAfterInsert(list<Policy__c> triggerNew, map<id,Policy__c> triggerOldMap)
{

}       
public void OnAfterUpdate(list<Policy__c> triggerNew, map<id,Policy__c> triggerOldMap,list<Policy__c> triggerOld)
{

}
*/
    public void OnBeforeInsert(list<Policy__c> triggerNew)
    {
        updatecontactid(triggerNew);
        updateChubbPolicyNumber(triggerNew);
        
        updatecontactname(triggerNew);
        
    }
    
    /* public void OnBeforeUpdate(list<Policy__c> triggerNew, map<id,Policy__c> triggerOldMap)
{

}
public void OnBeforeDelete(list<Policy__c> triggerOld, map<id,Policy__c> triggerOldMap)
{

}
public void OnAfterDelete(list<Policy__c> triggerOld, map<id,Policy__c> triggerOldMap)
{

}
public void OnAfterUnDelete(list<Policy__c> triggerNew)
{

}
*/ 
    
    public void updateChubbPolicyNumber(list<Policy__c> triggerNew ){
        try{
            
            list<Policy__c> latestPolicyRangeNB = new list<Policy__c>();
            list<Policy__c> latestPolicyRangeSB = new list<Policy__c>();
            list<Policy__c> latestPolicyRangeWC = new list<Policy__c>();
            
            // latestPolicyRangeNB = [SELECT id, Policy_Range_Number__c, Chubb_Policy_Number__c FROM Policy__c WHERE Underwriter_picklist__c ='Chubb' AND Chubb_Policy_Number__c != null 
            //                        AND Policy_Type_picklist__c ='Northbound' ORDER BY CreatedDate DESC LIMIT 1];
            // latestPolicyRangeSB = [SELECT id, Policy_Range_Number__c,Chubb_Policy_Number__c FROM Policy__c WHERE Underwriter_picklist__c ='Chubb' AND Chubb_Policy_Number__c != null 
            //                        AND Policy_Type_picklist__c !='Northbound' ORDER BY CreatedDate DESC LIMIT 1];
            
            // Integer northBoundRange = 247001;
            // Integer southBoundRange = 339001;

            // Modified for new range numbers of Northbound, southbound and watercraft policies.
            latestPolicyRangeNB = [SELECT id, Policy_Range_Number__c, Chubb_Policy_Number__c FROM Policy__c WHERE Underwriter_picklist__c ='Chubb' AND Chubb_Policy_Number__c != null 
                                   AND Policy_Type_picklist__c ='Northbound' ORDER BY CreatedDate DESC LIMIT 1];
            latestPolicyRangeSB = [SELECT id, Policy_Range_Number__c,Chubb_Policy_Number__c FROM Policy__c WHERE Underwriter_picklist__c ='Chubb' AND Chubb_Policy_Number__c != null 
                                   AND Policy_Type_picklist__c !='Northbound' AND Policy_Type_picklist__c !='Watercraft' ORDER BY CreatedDate DESC LIMIT 1];
            latestPolicyRangeWC = [SELECT id, Policy_Range_Number__c,Chubb_Policy_Number__c FROM Policy__c WHERE Underwriter_picklist__c ='Chubb' AND Chubb_Policy_Number__c != null 
                                  AND Policy_Type_picklist__c ='Watercraft' ORDER BY CreatedDate DESC LIMIT 1];
            Integer northBoundRange = 188001;
            Integer southBoundRange = 225001;
            Integer watercraftRange = 234500;
            
            if(!latestPolicyRangeNB.isEmpty()){
                northBoundRange = Integer.valueOf(latestPolicyRangeNB[0].Policy_Range_Number__c)+1;
            }            
            if(!latestPolicyRangeSB.isEmpty()){
                southBoundRange = Integer.valueOf(latestPolicyRangeSB[0].Policy_Range_Number__c)+1;
            }
            if(!latestPolicyRangeWC.isEmpty()){
                watercraftRange = Integer.valueOf(latestPolicyRangeWC[0].Policy_Range_Number__c)+1;
            }
            
            for(Policy__c policy: triggerNew){
                if(policy.Chubb_Policy_Number__c == null && policy.Underwriter_picklist__c != null && policy.Underwriter_picklist__c == 'Chubb'){
                    DateTime policyCreatedDate = policy.CreatedDate == null ? Date.today() : policy.CreatedDate;
                    String startYear = String.valueOf(( policyCreatedDate.year() - 2020 + 40 ));
                    
                    // if((policy.Policy_Type_picklist__c != null && policy.Policy_Type_picklist__c == 'Northbound') || test.isRunningTest()){
                    //     System.debug('northBoundRange > '+northBoundRange);
                    //     policy.Chubb_Policy_Number__c = 'RR '+ startYear+ northBoundRange;
                    //     northBoundRange = northBoundRange + 1;
                    //     System.debug('northBoundRange > '+northBoundRange);
                    //     System.debug('policy > '+policy.Chubb_Policy_Number__c);
                    // }
                    // else{
                    //     policy.Chubb_Policy_Number__c = 'NZ '+ startYear+ southBoundRange;
                    //     southBoundRange = southBoundRange + 1;
                    // } 
                    if((policy.Policy_Type_picklist__c != null && policy.Policy_Type_picklist__c == 'Northbound') ){
                        policy.Chubb_Policy_Number__c = 'RR '+ startYear+ northBoundRange;
                        northBoundRange = northBoundRange + 1;
                    }else if((policy.Policy_Type_picklist__c != null && policy.Policy_Type_picklist__c !='Northbound' && policy.Policy_Type_picklist__c !='Watercraft')){
                        policy.Chubb_Policy_Number__c = 'NZ '+ startYear+ southBoundRange;
                        southBoundRange = southBoundRange + 1;
                    }else if((policy.Policy_Type_picklist__c != null && policy.Policy_Type_picklist__c == 'Watercraft')){
                        policy.Chubb_Policy_Number__c = 'NZ '+ startYear+ watercraftRange;
                        watercraftRange = watercraftRange + 1;
                    }
                }
            }
        }
        catch(exception e){
            system.debug('message : '+ e.getMessage() + ' cause :'+ e.getCause() + ' Line number : '+e.getLineNumber());
        }
    }
    
    public void updatecontactid(list<Policy__c> triggerNew ){
        set<string> Accountset = new set<string>();
        map<string,string> ConatctMap = new map<string,string>();
        try{
            for(Policy__c policy: triggerNew  )
            {    
                if( policy.Contact__c == null ){
                    
                    Accountset.add(policy.Account_Policy__c);
                }
            }
            
            list<contact> contactlist = [select id,Accountid from contact where accountid IN: Accountset];
            
            for(contact cnt: contactlist )
            {
                ConatctMap.put(cnt.accountid,cnt.id);
            }
            
            for(Policy__c policy: triggerNew  )
            {
                if( policy.Contact__c == null ){
                    policy.Contact__c = ConatctMap.get(policy.Account_Policy__c);
                }
            }
        }
        catch(exception e) 
        {
            system.debug('message : '+ e.getMessage() + ' cause :'+ e.getCause() + ' Line number : '+e.getLineNumber());
        }
    }

    public static void updatecontactname(List<Policy__c> triggerNew){
        set<String> ContactId = new set<String>();
        set<String> AccountsId = new set<String>();

        try{
            for(Policy__c policy: triggerNew  ){
                if( policy.Contact__c != null && policy.Account_Policy__c != null){
                    ContactId.add(policy.Contact__c);
                    AccountsId.add(policy.Account_Policy__c);
                }
            }

            List<Driver__c> getDrivers = [SELECT Id, Name, First_Name__c, Last_Name__c, Policy__c, Phone__c, Account_Driver__c, Email__c, Address__c, Address_Line_2__c, City__c, 
                                          Country__c, Postal_Code__c, State_Province__c,  Contact__c, Dob__c FROM Driver__c 
                                          WHERE Contact__c IN: ContactId And (Driver_Type__c = 'Owner & Driver' OR Driver_Type__c = 'Owner') LIMIT 1];

            Contact contactGets =  [SELECT Id, Name, LastName, FirstName, Email, AccountId FROM Contact Where Id IN: ContactId LIMIT 1];

            Account AccDetail =  [SELECT Name, Email__c, Id FROM Account WHERE Id IN: AccountsId];

            if(AccDetail.Email__c != null && (AccDetail.Email__c == getDrivers[0].Email__c)) {
                AccDetail.Phone__c = getDrivers[0].Phone__c;
                AccDetail.Source__c = 'Portal';
                AccDetail.Street__c = getDrivers[0].Address__c;
                AccDetail.Street_2__c = getDrivers[0].Address_Line_2__c;
                AccDetail.City__c = getDrivers[0].City__c;
                AccDetail.Country__c = getDrivers[0].Country__c;
                AccDetail.Postal_Code__c = getDrivers[0].Postal_Code__c;
                AccDetail.State__c = getDrivers[0].State_Province__c;

                update AccDetail;
            }

           if(contactGets.Email != null && (contactGets.Email == getDrivers[0].Email__c)) {
                contactGets.Date_of_Birth__c = getDrivers[0].Dob__c;
                contactGets.MobilePhone = getDrivers[0].Phone__c;
                contactGets.Street__c = getDrivers[0].Address__c;
                contactGets.Street_2__c = getDrivers[0].Address_Line_2__c;
                contactGets.City__c = getDrivers[0].City__c;
                contactGets.Country__c = getDrivers[0].Country__c;
                contactGets.Postal_Code__c = getDrivers[0].Postal_Code__c;
                contactGets.State__c = getDrivers[0].State_Province__c;

                Update contactGets;
            }

            /*if(contactGets !=  null){
                User userDetail = [SELECT Id, Name From user where Email =:contactGets.Email];
                if(userDetail.Name.contains('New Lead') || userDetail.Name.contains('Insurance')){
                    userDetail.FirstName = getDrivers[0].First_Name__c;
                    userDetail.LastName = getDrivers[0].Last_Name__c;
                    userDetail.Alias = getDrivers[0].First_Name__c.charAt(0) + getDrivers[0].Last_Name__c.substring(0,5);
                    
                    update userDetail;
                }
            }*/
        } catch(exception ex){
            system.debug('message : '+ ex.getMessage() + ' line Number : '+ ex.getLineNumber());
        }
    }
}