force-app/main/default/objects/Driver__c/fields/Account_Driver__c.field-meta.xml
<CustomField>
    <fullName>Account_Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/default__c.field-meta.xml
<CustomField>
    <fullName>default__c</fullName>
    <label>Default</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Dob__c.field-meta.xml
<CustomField>
    <fullName>Dob__c</fullName>
    <label>DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TriggerBatchTest.cls
@isTest
public class TriggerBatchTest {
    @isTest
    public static void validateTrigger(){
        Account objAccount = new Account(Name = 'Test Driver', Email__c = 'test@test.com', Username__c = 'test@test.com');
        insert objAccount;
        Contact objContact = new Contact(LastName = 'Test Driver', Email = 'test@test.com');
        insert objContact;
        Driver__C objDriver = new Driver__c(Account_Driver__c = objAccount.Id, Name = 'Test Driver', Dob__c = system.today(), default__c = 'Yes');
        insert objDriver;
        
        objContact.Date_Of_Birth__c = system.today().addDays(-10);
        update objContact;
        objDriver.Dob__c = system.today().addDays(-20);
        update objDriver;
    }
    @isTest
    public static void validateBatch(){
        Account objAccount = new Account(Name = 'Test Driver', Email__c = 'test@test.com', Username__c = 'test@test.com');
        insert objAccount;
        Contact objContact = new Contact(LastName = 'Test Driver', Email = 'test@test.com');
        insert objContact;
        Driver__C objDriver = new Driver__c(Account_Driver__c = objAccount.Id, Name = 'Test Driver', Dob__c = system.today(), default__c = 'Yes');
        insert objDriver;
        
        UpdateBirthdateOnContactBatch objBatch = new UpdateBirthdateOnContactBatch();
        database.executeBatch(objBatch);
    }
}