force-app/main/default/objects/Driver__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <label>Address (Line 2)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Driver_Type__c.field-meta.xml
<CustomField>
    <fullName>Driver_Type__c</fullName>
    <label>Driver Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Co-Owner</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Owner &amp; Driver</fullName>
            </value>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Quote_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote (c)</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quoted Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Watercraft__c.field-meta.xml
<CustomField>
    <fullName>Watercraft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Watercraft</label>
    <referenceTo>Watercraft__c</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Account_Policy__c.field-meta.xml
<CustomField>
    <fullName>Account_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Medical_picklist__c.field-meta.xml
<CustomField>
    <fullName>Medical_picklist__c</fullName>
    <label>Medical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Medical</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automobile</fullName>
            </value>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Motorcycle/Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Northbound</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Quote_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote (c)</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Vehicle_Policy__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle(Policy)</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Watercraft__c.field-meta.xml
<CustomField>
    <fullName>Watercraft__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Watercraft</label>
    <referenceTo>Watercraft__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Company_City__c.field-meta.xml
<CustomField>
    <fullName>Company_City__c</fullName>
    <label>Company City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Company_State__c.field-meta.xml
<CustomField>
    <fullName>Company_State__c</fullName>
    <label>Company State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Vehicle</relationshipLabel>
    <relationshipName>Vehicle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Quote_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote (c)</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quoted Vehicle</relationshipLabel>
    <relationshipName>Vehicle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Owner_Address__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Owner_Address__c</fullName>
    <inlineHelpText>Address of vehicle owner</inlineHelpText>
    <label>Vehicle Owner Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Owner_City__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Owner_City__c</fullName>
    <label>Vehicle Owner City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Owner_Name__c</fullName>
    <label>Vehicle Owner Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Owner_State__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Owner_State__c</fullName>
    <label>Vehicle Owner State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeclarationPageInsuranceControllerTest.cls
@isTest
public class DeclarationPageInsuranceControllerTest {
    
 public static testMethod void Declaration_Page_Insurance_Controller(){ 
        TriggerSwitch__c customsetting = new TriggerSwitch__c();
        customsetting.Name = 'PolicyTrigger';
        customsetting.Active__c = false;
        insert customsetting;
        Watercraft__c watercraftrecord = new Watercraft__c();
        watercraftrecord.year__c = '2010';
        insert watercraftrecord;
        List <Driver__c> drive = new List <Driver__c>();
        for(integer i=0; i<2; i++){
            Driver__c drivers = new Driver__c ();
            if(i==0){
                drivers.Driver_Type__c = 'Owner';
            }else{
                drivers.Driver_Type__c = 'Driver';
            }            
            drivers.First_Name__c = 'test'+ i;
            drivers.Last_Name__c = 'test last'+ i;
            drivers.Address_Line_2__c = 'address line'+ i;
            drivers.Address__c = 'address line2'+ i;
            drive.add(drivers);
        }
        insert drive;
        /*Driver__c onlyDriver = new Driver__c();
        onlyDriver.Driver_Type__c = 'Driver';
        onlyDriver.First_Name__c = 'test Driver';
        onlyDriver.Last_Name__c = 'test Driver last';
        onlyDriver.Address_Line_2__c = 'Driver address line';
        onlyDriver.Address__c = 'Driver address line2';        
        insert onlyDriver;*/
        Account acc = new Account();
        acc.Name = 'testAccount';
        
        insert acc;
        
        Vehicle__c vehiclePolicy = new Vehicle__c();
        vehiclePolicy.Vehicle_Owner_Name__c = 'Test Owner';
        vehiclePolicy.Company_Name__c = 'Test company';
        vehiclePolicy.Vehicle_Owner_Address__c = 'Test address';
        vehiclePolicy.Company_Address__c = 'Test address';
        vehiclePolicy.Company_City__c = 'Test city';
        vehiclePolicy.Vehicle_Owner_City__c = 'Test city';
         vehiclePolicy.Vehicle_Owner_State__c = 'Test state';
         vehiclePolicy.Company_State__c = 'Test state';
        insert vehiclePolicy;
        
        Contact policyContact = new Contact();
        policyContact.FirstName = 'Test';
        policyContact.LastName = ' contact';
        policyContact.Street__c = 'Contact street';
        insert policyContact;
        
        Policy__c policyrecord=new policy__c();
        Time myTime = Time.newInstance(1, 2, 3, 4);
        Time expected = Time.newInstance(4, 2, 3, 4);
        policyrecord.name='policy';
        policyrecord.Account_Policy__c = acc.Id;
        policyrecord.Policy_Type_picklist__c = 'Northbound';
        policyrecord.Start_Time__c =  myTime;
        policyrecord.End_Time__c =  expected;
        policyrecord.Watercraft__c = watercraftrecord.Id;
        policyRecord.Medical_picklist__c = '2,000/10,000';
        policyrecord.Vehicle_Policy__c = vehiclePolicy.Id;
        policyrecord.Contact__c = policyContact.Id;
        insert policyrecord;
        Quote__c quotes = new Quote__c ();
        date myDate = date.newInstance(1988, 12, 17);
        quotes.Date_of_Birth__c = myDate;
        insert quotes;
        
        
        List <Quote_Driver__c> quotedrive = new List <Quote_Driver__c>();
        for(integer i= 0; i<drive.size(); i++){
            Quote_Driver__c quotedriver = new Quote_Driver__c();
            quotedriver.Driver__c = drive[i].Id;
            quotedriver.Quote_c__c = quotes.id;
            quotedriver.Policy__c = policyrecord.id ;
            quotedrive.add(quotedriver);  
        }
        insert quotedrive;
        test.startTest();
        PageReference pgRef = Page.Southbound_PolicyDec_Chubb; 
        Test.setCurrentPage(pgRef);
        ApexPages.currentPage().getParameters().put('id', policyrecord.Id);
        // System.currentPageReference().getParameters().put('params', 'CRLAL-22-DXQL4');
        Declaration_Page_Insurance_Controller controller = new Declaration_Page_Insurance_Controller() ; 
        test.stopTest();   
    }
    public static testMethod void getFormattedStartTime_Method(){
        test.startTest();
        PageReference pgRef = Page.Declaration_Page_Insurance; 
        Test.setCurrentPage(pgRef);
        ApexPages.currentPage().getParameters().put('id', '00B1C000008UeA61');
        Declaration_Page_Insurance_Controller decl = new Declaration_Page_Insurance_Controller();
        decl.getFormattedStartTime();
        test.stopTest();  
    }
    public static testMethod void getFormattedEndTime_Method(){
        test.startTest();      
        Declaration_Page_Insurance_Controller decl = new Declaration_Page_Insurance_Controller();
        decl.getFormattedEndTime();
        test.stopTest();  
    }
    }