force-app/main/default/objects/Driver__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <label>Address (Line 2)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/default__c.field-meta.xml
<CustomField>
    <fullName>default__c</fullName>
    <label>Default</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Driver_Type__c.field-meta.xml
<CustomField>
    <fullName>Driver_Type__c</fullName>
    <label>Driver Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Co-Owner</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Owner &amp; Driver</fullName>
            </value>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Quote_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote (c)</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quoted Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_type__c.field-meta.xml
<CustomField>
    <fullName>Policy_type__c</fullName>
    <label>Policy_Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automobile</fullName>
            </value>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Motorcycle/Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Northbound</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Quote_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote (c)</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Underwriter__c</fullName>
    <label>Underwriter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chubb</fullName>
            </value>
            <value>
                <fullName>Mapfre</fullName>
            </value>
            <value>
                <fullName>Qualitas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Vehicle_type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_type__c</fullName>
    <label>Vehicle_Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Limited</fullName>
            </value>
            <value>
                <fullName>Max</fullName>
            </value>
            <value>
                <fullName>LiabilityTheft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Driver_Age__c.field-meta.xml
<CustomField>
    <fullName>Driver_Age__c</fullName>
    <label>Driver Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/End_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>End_Date_for_Coverage__c</fullName>
    <label>End Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Liability</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Medical</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Start_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_for_Coverage__c</fullName>
    <label>Start Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>90 Day</fullName>
            </value>
            <value>
                <fullName>Semi-Annual(Half a Year)</fullName>
            </value>
            <value>
                <fullName>Annual(One Year)</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Territory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Towed_Unit__c.field-meta.xml
<CustomField>
    <fullName>Towed_Unit__c</fullName>
    <label>Towed Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Policy_Type_picklist__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Quote_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote (c)</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quoted Vehicle</relationshipLabel>
    <relationshipName>Vehicle</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automobile/Sedan</fullName>
            </value>
            <value>
                <fullName>Pickup Truck w or w/o Camper Shell</fullName>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
            <value>
                <fullName>Van</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Motor Home / RV</fullName>
            </value>
            <value>
                <fullName>ATV</fullName>
            </value>
            <value>
                <fullName>Boat</fullName>
            </value>
            <value>
                <fullName>Car/Truck/Auto</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PolicyEditRenewUtilsTest.cls
@isTest
public class PolicyEditRenewUtilsTest {
    
    @isTest
    static void fetchPolicyDetails_testCase1(){
        TriggerSwitch__c customset = new TriggerSwitch__c();
        customset.Name='PolicyTrigger';
        customset.Active__c=FALSE;
        insert customset;
        
        Quote__c quote = new Quote__c();
        quote.Start_Date_for_Coverage__c= system.today();
        quote.End_Date_for_Coverage__c= system.today()+5;
        quote.Driver_Age__c = 80;
        
        quote.Underwriter__c ='Chubb';
        quote.Coverage__c='Complete';
        quote.Territory__c='  Full';
        quote.Term__c='Daily';
        quote.Policy_Type_picklist__c='Northbound';
        quote.Vehicle_Type__c = 'Automobile';
        quote.Medical__c='2,000/10,000';
        quote.Liability__c='100,000'; 
        quote.Date_of_Birth__c = date.newinstance(1950,10,12);
        quote.Towed_Unit__c = 'true';
        quote.Start_Time__c = Time.newInstance(1, 0, 0, 0);
        quote.End_Time__c = Time.newInstance(1, 0, 0, 0);
        
        String quoteRecord = JSON.serialize(quote);
        quote.Towed_Unit__c = 'Yes';
        insert quote;
        List<driver__c> drivers = new List<driver__c>();
        driver__c driver =new driver__c();
        driver.Quote_c__c = quote.Id;
        driver.First_Name__c='d';
        driver.Last_Name__c='s';
        driver.email__c='s@gmail.com';
        driver.Driver_Type__c='Owner';
        driver.Phone__c='123';
        driver.Address__c ='address';
        driver.Address_Line_2__c = 'address';
        driver.City__c = 'city';
        driver.Country__c = 'country';
        driver.default__c = 'Yes';
        drivers.add(driver);
        insert drivers;
        
        Quote_Driver__c qtd = new Quote_Driver__c();
        qtd.Driver__c = driver.Id;
        qtd.Quote_c__c = quote.Id;
        insert qtd;
        
        vehicle__c vehicle = new vehicle__c();
        vehicle.Company_Name__c ='northbund';
        vehicle.Company_Address__c='abc';
        vehicle.type__c='car';
        vehicle.model__c='suv';
        vehicle.make__c='ford';
        vehicle.year__c='2020';
        insert vehicle;
        
        
        Legal_Term__c legalterm = new Legal_Term__c();
        legalterm.Terms_of_Purchase_and_Use__c = 'No';
        legalterm.Underwriter__c = 'Chubb';
        legalterm.Policy_Type__c = 'Watercraft';        
        insert legalterm;
        
        List<Towed_Unit__c> towedUnitsData = new List<Towed_Unit__c>();
        Towed_Unit__c towunit = new Towed_Unit__c();
        towunit.Quote_c__c = quote.Id;
        //insert towunit;
        towedUnitsData.add(towunit);
        insert towedUnitsData;
        Quote_Towed_Unit__c towedQUotes = new Quote_Towed_Unit__c();
        towedQUotes.Towed_Unit__c = towunit.Id;
        towedQUotes.Quote_c__c = quote.Id;
        insert towedQUotes;
        
        
        Policy__c policy = new Policy__c();
        policy.Quote_c__c = quote.Id;
        insert policy;
        Test.setMock(HttpCalloutMock.class, new Mex_Insurance_Mock());
        Test.startTest();
        PolicyEditRenewUtils.fetchPolicyDetails(policy.Id);
        PolicyEditRenewUtils.fetchPolicyQuoteDetails(quote.Id);
        PolicyEditRenewUtils.fetchPolicyVehicleDetails(vehicle.Id);
        PolicyEditRenewUtils.fetchPolicyDriverDetails(quote.Id);
        PolicyEditRenewUtils.fetchPolicyTowedDetails(quote.Id);
        PolicyEditRenewUtils.fetchUpdatedDate(Date.today(),'Semi-Annual(Half a Year)');
        PolicyEditRenewUtils.fetchUpdatedDate(Date.today(),'Annual');
        PolicyEditRenewUtils.fetchDateRelatedInfo();
        PolicyEditRenewUtils.createNewEditPolicyFromCash(JSON.serialize(vehicle),JSON.serialize(drivers),JSON.serialize(towedUnitsData),quote.Id,policy.Id,false);
        PolicyEditRenewUtils.createNewEditPolicyFromCash(JSON.serialize(vehicle),JSON.serialize(drivers),JSON.serialize(towedUnitsData),quote.Id,policy.Id,true);
        PolicyEditRenewUtils.createNewEditPolicyFromCashWithAmount(JSON.serialize(vehicle),JSON.serialize(drivers),JSON.serialize(towedUnitsData),quote.Id,policy.Id,false,230);
        PolicyEditRenewUtils.createNewEditPolicyFromCashWithAmount(JSON.serialize(vehicle),JSON.serialize(drivers),JSON.serialize(towedUnitsData),quote.Id,policy.Id,true,230);
        Test.stopTest();
    }
}