force-app/main/default/objects/Driver__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Driver_Age__c.field-meta.xml
<CustomField>
    <fullName>Driver_Age__c</fullName>
    <label>Driver Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Is_there_a_driver_over_75__c.field-meta.xml
<CustomField>
    <fullName>Is_there_a_driver_over_75__c</fullName>
    <label>Is there a driver over 75</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Is_there_a_driver_under_21__c.field-meta.xml
<CustomField>
    <fullName>Is_there_a_driver_under_21__c</fullName>
    <label>Is there a driver under 21</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
            <value>
                <fullName>true</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Status__c.field-meta.xml
<CustomField>
    <fullName>Quote_Status__c</fullName>
    <label>Quote Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Policy Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DriverDetailController.cls
public without sharing class DriverDetailController {

    @AuraEnabled 
    public static DriverDetailResponse processDriverDetails(String serializedLeadRecord, Quote__c quoteRecord) {
        try{
             Database.UpsertResult leadUpsertResult;
        Database.UpsertResult quoteUpsertResult;
        DriverDetailResponse detailResponse = new DriverDetailResponse();

        Map<String, Object> ldObjectMap = new Map<String, Object>();
        ldObjectMap = (Map<String, Object>) JSON.deserializeUntyped(serializedLeadRecord);
            System.debug('Line 12 Running '+ldObjectMap);
        String leadId = Mex_Insurance_Calloututility.getLeadId(ldObjectMap);
                        System.debug('Line 13 Running '+leadId);

        String userType = UserInfo.getUserType();

        Lead leadRecord = (Lead) JSON.deserialize(serializedLeadRecord, Lead.class);

        if( (userType.equalsIgnoreCase('Guest') && (leadId == null || leadId == '')) || Test.isRunningTest() ){
            leadRecord.Company = 'Driver Licence Insurance';
            leadRecord.Status = 'New';
            leadUpsertResult = Database.upsert(leadRecord, Lead.Email, false);
            leadId = leadRecord.Id;
        }

        if (leadId != null ) {
            quoteRecord.Lead__c = leadId;

            List<Lead> leads = new List<Lead>();
            leads = [SELECT Id, ConvertedAccountId, ConvertedContactId FROM Lead WHERE Id = :leadId AND IsConverted = TRUE LIMIT 1];
            if (leads != null && !leads.isEmpty()) {
                quoteRecord.Contact__c = leads[0].ConvertedContactId;
                quoteRecord.Account__c = leads[0].ConvertedAccountId;
            }
            quoteRecord.Lead__c = leadId;
            leadRecord.Id = leadId;
        }

        if (leadId != null) {
            
            quoteRecord.Date_of_Birth__c = leadRecord.Date_of_Birth__c;
            quoteRecord.Underwriter__c = 'Chubb';
            quoteRecord.Policy_Type_picklist__c = 'Driver License';
            quoteRecord.Quote_Status__c = 'Draft';

            /*if (leadRecord.IsConverted) {
                quoteRecord.Contact__c = leadRecord.ConvertedContactId;
                quoteRecord.Account__c = leadRecord.ConvertedAccountId;
            } else {
                List<User> currentUser = [
                        SELECT Id, ContactId, Contact.AccountId
                        FROM User
                        WHERE Id = :UserInfo.getUserId()
                        LIMIT 1
                ];
                if (!currentUser.isEmpty()) {
                    quoteRecord.Contact__c = currentUser[0].ContactId;
                    quoteRecord.Account__c = currentUser[0].Contact.AccountId;
                }
            }*/

            if (quoteRecord.Date_of_Birth__c != null) {
                Integer year = System.today().year() - quoteRecord.Date_of_Birth__c.year();
                quoteRecord.Is_there_a_driver_under_21__c = year < 21 ? 'Yes' : 'No';
                quoteRecord.Is_there_a_driver_over_75__c = year > 75 ? 'Yes' : 'No';
                quoteRecord.Driver_Age__c = year;
            }
            quoteUpsertResult = Database.upsert(quoteRecord);
        }

        if ( quoteUpsertResult != null && quoteUpsertResult.isSuccess()) {
            detailResponse.leadRecord = leadRecord;
            detailResponse.quoteRecord = quoteRecord;
        } else {
            String errorMessage = '';
            if (!leadUpsertResult.isSuccess() && !leadUpsertResult.getErrors().isEmpty()) {
                errorMessage += 'Lead insert issue: ' + leadUpsertResult.getErrors()[0].getMessage();
            }

            if (quoteUpsertResult != null && !quoteUpsertResult.isSuccess() && !quoteUpsertResult.getErrors().isEmpty()) {
                errorMessage += 'Quote upsert issue: ' + quoteUpsertResult.getErrors()[0].getMessage();
            }
            detailResponse.errorMessage = errorMessage;
        }

        System.debug('detailResponse : ' + detailResponse);
        return detailResponse;
        }catch( Exception ex){
             system.debug('Exception'+ex.getMessage()+'at'+ex.getLineNumber());
             return null ;
            
        }
    }

    @AuraEnabled
    public static List<Driver__c> getCurrentUserDrivers() {
        return QuickQuotationCtrl.getCurrentUserDrivers();
    }

    @AuraEnabled
    public static Map<String, Object> createDriverAction(Driver__c driverRecord, String quoteId, 
        Boolean isOwner, String watercraftId, Boolean Primary_insured) {
        return QuickQuotationCtrl.createDriverAction( driverRecord, quoteId, isOwner, watercraftId,  Primary_insured);
    }

    @AuraEnabled
    public static Map<String, Object> checkalreadyExistUserAction(String emailAdder) {
        return QuickQuotationCtrl.checkalreadyExistUserAction(emailAdder);
    }

    public class DriverDetailResponse {
        @AuraEnabled
        public Boolean isSuccess;
        @AuraEnabled
        public Lead leadRecord;
        @AuraEnabled
        public Quote__c quoteRecord;
        @AuraEnabled
        public String errorMessage;
        public DriverDetailResponse() {
        }
    }
}