force-app/main/default/objects/Driver__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Quote_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote (c)</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quoted Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/I_V_A_Mex_Tax__c.field-meta.xml
<CustomField>
    <fullName>I_V_A_Mex_Tax__c</fullName>
    <label>I.V.A. / Mex. Tax:</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Liability_picklist__c.field-meta.xml
<CustomField>
    <fullName>Liability_picklist__c</fullName>
    <label>Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Liability</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Medical_picklist__c.field-meta.xml
<CustomField>
    <fullName>Medical_picklist__c</fullName>
    <label>Medical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Medical</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Net_Premium__c.field-meta.xml
<CustomField>
    <fullName>Net_Premium__c</fullName>
    <label>Net Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automobile</fullName>
            </value>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Motorcycle/Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Northbound</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Quote_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_c__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote (c)</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status_picklist__c.field-meta.xml
<CustomField>
    <fullName>Status_picklist__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Term_days__c.field-meta.xml
<CustomField>
    <fullName>Term_days__c</fullName>
    <label>Term_Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Territory_picklist__c.field-meta.xml
<CustomField>
    <fullName>Territory_picklist__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Territory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Total_Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Transaction_Amount__c</fullName>
    <label>Total Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Underwriter__c</fullName>
    <label>Underwriter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chubb</fullName>
            </value>
            <value>
                <fullName>Mapfre</fullName>
            </value>
            <value>
                <fullName>Qualitas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter_picklist__c.field-meta.xml
<CustomField>
    <fullName>Underwriter_picklist__c</fullName>
    <label>Underwriter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chubb</fullName>
            </value>
            <value>
                <fullName>Mapfre</fullName>
            </value>
            <value>
                <fullName>Qualitas</fullName>
            </value>
            <value>
                <fullName>GNP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Broker_Policy_Fee__c.field-meta.xml
<CustomField>
    <fullName>Broker_Policy_Fee__c</fullName>
    <label>Broker/Policy Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/End_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>End_Date_for_Coverage__c</fullName>
    <label>End Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Liability__c.field-meta.xml
<CustomField>
    <fullName>Liability__c</fullName>
    <label>Liability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Liability</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Medical</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Value__c.field-meta.xml
<CustomField>
    <fullName>Quote_Value__c</fullName>
    <label>Quote Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Start_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_for_Coverage__c</fullName>
    <label>Start Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>90 Day</fullName>
            </value>
            <value>
                <fullName>Semi-Annual(Half a Year)</fullName>
            </value>
            <value>
                <fullName>Annual(One Year)</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Term_Days__c.field-meta.xml
<CustomField>
    <fullName>Term_Days__c</fullName>
    <label>Term Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Territory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Towed_Unit__c.field-meta.xml
<CustomField>
    <fullName>Towed_Unit__c</fullName>
    <label>Towed Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataService.cls
public with sharing class TestDataService {

    public static ContactService.CreditCard createCreditCard() {
        ContactService.CreditCard creditCard = new ContactService.CreditCard();
        creditCard.cardId = '10000000';
        creditCard.name = 'Test Test';
        creditCard.address1 = 'Test Address';
        creditCard.address2='Test Address 2';
        creditCard.code='205201';
        creditCard.city = 'Los Angeles';
        creditCard.state = 'CA';
        creditCard.zip = '1111111';
        creditCard.country = 'US';
        creditCard.cardNumber = '4111111111111111';
        creditCard.cardType = 'Visa';
        creditCard.year = '2024';
        creditCard.month = '11';
        return creditCard;
    }

    public static Contact createContact(Boolean performInsert) {
        Contact contact = new Contact(
            Email = 'test@test.test',
            LastName = 'Test',
            MailingCity = 'Test'
        );
        if (performInsert) {
            insert contact;
        }
        return contact;
    }

    public static Authorize_Net_Customer_Profile__c createCustomerProfile(Boolean performInsert, Id contactId) {
        Authorize_Net_Customer_Profile__c customerProfile = new Authorize_Net_Customer_Profile__c(
            Contact__c = contactId,
            Profile_Id__c = '11111'
        );
        if (performInsert) {
            insert customerProfile;
        }
        return customerProfile;
    }

    public static Authorize_Net_Payment_Profile__c createPaymentProfile(Boolean performInsert, Id customerProfileId) {
        Authorize_Net_Payment_Profile__c paymentProfile = new Authorize_Net_Payment_Profile__c(
            Authorize_Net_Customer_Profile__c = customerProfileId,
            Payment_Profile_Id__c = '22222'
        );
        if (performInsert) {
            insert paymentProfile;
        }
        return paymentProfile;
    }

    public static Quote__c createQuote(Boolean performInsert) {
        Quote__c quote = new Quote__c(
            Policy_Type_picklist__c = 'Driver License',
            Quote_Value__c = 130.50,
            Start_Date_for_Coverage__c = Date.today(),
            End_Date_for_Coverage__c = Date.today().addYears(1),
            I_V_A_Mex_Tax__c = 13.50,
            Broker_Policy_Fee__c = 50,
            Term__c = 'Annual(One Year)'
        );
        if (performInsert) {
            insert quote;
        }
        return quote;
    }
     public static Quote__c createQuoteTest1(Boolean performInsert, string picklist, string leadId, string accId) {
        Quote__c quote = new Quote__c(
            Policy_Type_picklist__c = picklist,
            Lead__c = leadId,
            contact__c = createContact(true).Id,
            Account__c = accId,
            Quote_Value__c = 130.50,
            Start_Date_for_Coverage__c = Date.today(),
            End_Date_for_Coverage__c = Date.today().addYears(1),
            I_V_A_Mex_Tax__c = 13.50,
            Broker_Policy_Fee__c = 50,
            Term__c = 'Annual(One Year)'
        );
        if (performInsert) {
            insert quote;
        }
        return quote;
    }
    public static list<Towed_Unit__c> createtowed(){
        List<Towed_Unit__c> ListTowedUnit = new List<Towed_Unit__c>();
        for(integer i=0;i<=5;i++){
        Towed_Unit__c newtowed= new Towed_Unit__c(); 
        newtowed.Make__c='BMW'+i;
        newtowed.Model__c='X7'+i;
        newtowed.Towed_Unit_Value__c=40+i;
        newtowed.Days_in_Tow__c=4+i;
        ListTowedUnit.add(newtowed);
        }
       
        insert ListTowedUnit;
        return ListTowedUnit; 
    }
    
    public static Driver__c createDriver(){
         Driver__c dreiver = new Driver__c();
          dreiver.Name='test';
          dreiver.Address__c='test Address';
          insert dreiver;
         return dreiver;
        
    }
    
    
    
    
    public static TransactionService.PaymentTransaction createPaymentTransaction(String quoteId, String customerProfileId, String paymentProfileId) {
        TransactionService.PaymentTransaction paymentTransaction = new TransactionService.PaymentTransaction();
        paymentTransaction.quoteIds = new List<String>{quoteId};
        paymentTransaction.customerProfileId = customerProfileId;
        paymentTransaction.paymentProfileId = paymentProfileId;
        return paymentTransaction;
    }

    public static Authorize_Net_Log_Event__e createAuthorizeNetLogEvent(Boolean publishEvent) {
        Authorize_Net_Log_Event__e event = new Authorize_Net_Log_Event__e(
            Type__c = 'error',
            Contact__c = null,
            Description__c = 'error',
            Full_Message__c = 'error'
        );
        if (publishEvent) {
            EventBus.publish(event);
        }
        return event;
    }

    public static List<Subscription__c> createSubscriptions(Integer numberOfRecords, Id parentQuoteId, Id parentContactId) {
        List<Subscription__c> subscriptions = new List<Subscription__c>();

        for (Integer i = 0; i < numberOfRecords; i++) {
            subscriptions.add(new Subscription__c(
                Subscription_Id__c = String.valueOf(1234567 + i),
                Description__c = 'Test Subscription ' + i,
                Contact__c = parentContactId,
                Amount__c = 200 + i,
                Trial_Amount__c = 0,
                Total_Occurrences__c = 0,
                Trial_Occurrences__c = 0,
                Start_Date__c = Date.today(),
                Next_Payment_Date__c = Date.today(),
                Length__c = 12,
                Unit__c = 'months',
                Quote__c = parentQuoteId
            ));
        }

        insert subscriptions;

        return subscriptions;
    }

    public static Policy__c createPolicy(Quote__c quote) {
        Policy__c policy = new Policy__c();
        policy.Broker_Policy_Fee__c = quote.Broker_Policy_Fee__c;
        policy.I_V_A_Mex_Tax__c = quote.I_V_A_Mex_Tax__c;
        policy.Net_Premium__c = quote.Net_Premium__c;
        policy.Policy_Type_picklist__c = quote.Policy_Type_picklist__c;
        policy.Quote_c__c = quote.Id;

        policy.Status_picklist__c = 'Active';
        
        if( quote.Start_Date_for_Coverage__c != null ){
            policy.Start_Date__c = quote.Start_Date_for_Coverage__c;
        }
        
        if( quote.End_Date_for_Coverage__c != null ){
            policy.End_Date__c = quote.End_Date_for_Coverage__c;
        }

        policy.Total_Transaction_Amount__c = quote.Quote_Value__c;
        policy.Medical_picklist__c = quote.Medical__c;
        policy.Liability_picklist__c = quote.Liability__c;
        policy.Territory_picklist__c = quote.Territory__c;
        policy.Term__c = quote.Term__c;
        policy.Term_days__c = quote.Term_days__c; 
        policy.Underwriter_picklist__c = quote.Underwriter__c;
        policy.Vehicle_type__c = quote.Vehicle_type__c;
        policy.Insured_value__c = quote.Vehicle_Value__c;

        insert policy;

        return policy;
    }
}