force-app/main/default/objects/Driver__c/fields/Dob__c.field-meta.xml
<CustomField>
    <fullName>Dob__c</fullName>
    <label>DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Drivers</relationshipLabel>
    <relationshipName>Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State / Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automobile</fullName>
            </value>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Motorcycle/Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Northbound</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Underwriter__c.field-meta.xml
<CustomField>
    <fullName>Underwriter__c</fullName>
    <label>Underwriter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chubb</fullName>
            </value>
            <value>
                <fullName>Mapfre</fullName>
            </value>
            <value>
                <fullName>Qualitas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Coverage__c.field-meta.xml
<CustomField>
    <fullName>Coverage__c</fullName>
    <label>Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Liability</fullName>
            </value>
            <value>
                <fullName>Limited</fullName>
            </value>
            <value>
                <fullName>Max</fullName>
            </value>
            <value>
                <fullName>LiabilityTheft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/End_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>End_Date_for_Coverage__c</fullName>
    <label>End Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Medical__c.field-meta.xml
<CustomField>
    <fullName>Medical__c</fullName>
    <label>Medical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Medical</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Start_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_for_Coverage__c</fullName>
    <label>Start Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DriverLicenceFlowController.cls
public without sharing class DriverLicenceFlowController {
    private final static String GUEST_USER_TYPE = 'Guest';
    @AuraEnabled
    public static DriverLicenseFlowData getInitData(String policyType) {
        DriverLicenseFlowData initData = new DriverLicenseFlowData();
        String userType = UserInfo.getUserType();
        initData.isCommunityUser = !userType.equalsIgnoreCase(GUEST_USER_TYPE);
        initData.quoteRecord.Underwriter__c = 'Chubb';
        initData.quoteRecord.Coverage__c = 'Liability';
        initData.quoteRecord.Medical__c = '5,000/25,000';
        initData.quoteRecord.Policy_Type_picklist__c = policyType;

        if (initData.isCommunityUser) {
            User currentUser = getCurrentUser();
            initData.leadRecord.Date_of_Birth__c = currentUser?.Contact.Date_of_Birth__c;
            initData.leadRecord.Email = currentUser?.Email;

            initData.quoteRecord.Date_of_Birth__c = currentUser.Contact.Date_of_Birth__c;
            initData.driverRecord.First_Name__c = currentUser.FirstName;
            initData.driverRecord.Last_Name__c = currentUser.LastName;
            initData.driverRecord.Email__c = currentUser.Email;
            initData.driverRecord.Dob__c = currentUser.Contact.Date_of_Birth__c;
            initData.driverRecord.Phone__c = currentUser.Phone;
            initData.driverRecord.Address__c = currentUser.Contact.MailingStreet;
            initData.driverRecord.City__c = currentUser.Contact.MailingCity;
            initData.driverRecord.State_Province__c = currentUser.Contact.MailingState;
            initData.driverRecord.Postal_Code__c = currentUser.Contact.MailingPostalCode;
            initData.driverRecord.Country__c = currentUser.Contact.MailingCountry;
        }
        // TODO: debug only
//        initData.leadRecord.FirstName = 'John';
//        initData.leadRecord.LastName = 'Smith';
//        initData.leadRecord.Phone = '555-45-67';
//        initData.leadRecord.Email = 'example@gmail.com';
//        initData.leadRecord.Street = 'Washington st.';
//        initData.leadRecord.City = 'Austin';
//        initData.leadRecord.State = 'Texas';
//        initData.leadRecord.Country = 'United States';
//        initData.leadRecord.PostalCode = '77449';
//        initData.leadRecord.Date_of_Birth__c = Date.today().addYears(-33).addMonths(-5).addDays(-10);
//
//        initData.quoteRecord.Start_Date_for_Coverage__c = Date.today().addDays(11);
//        initData.quoteRecord.End_Date_for_Coverage__c = Date.today().addDays(376);
//         end: debug only

        return initData;
    }

    public class DriverLicenseFlowData {
        @AuraEnabled
        public Boolean isCommunityUser;
        @AuraEnabled
        public Lead leadRecord;
        @AuraEnabled
        public Driver__c driverRecord;
        @AuraEnabled
        public Quote__c quoteRecord;

        public DriverLicenseFlowData() {
            leadRecord = new Lead();
            driverRecord = new Driver__c();
            quoteRecord = new Quote__c();
        }
    }

    @AuraEnabled
    public static User getCurrentUser() {
        return [
                SELECT Id, Email, FirstName, LastName, Phone, ContactId, Contact.Email, Contact.Birthdate,
                        Contact.Date_of_Birth__c, Contact.AccountId, Contact.MailingState, Contact.MailingCity,
                        Contact.MailingStreet, Contact.MailingPostalCode, Contact.MailingCountry
                FROM User
                WHERE Id = :UserInfo.getUserId()
                LIMIT 1
        ][0];
    }

    @AuraEnabled
    public static Map<String, Object> createTransactionAction(String rateRecordList, String affiliateAccountString) {
        return QuickQuotationCtrl.createTransactionAction(rateRecordList, affiliateAccountString);
    }

    @AuraEnabled
    public static Map<String, Object> updatePolicyAction(Contact contactRecord, Policy__c policyRecord, String leadIds, String quoteIds) {
        return QuickQuotationCtrl.updatePolicyAction(contactRecord, policyRecord, leadIds, quoteIds);
    }

    @AuraEnabled
    public static Account retrieveAffiliateAccount(String affiliateNumber) {
        Account acc = [
                SELECT Id
                FROM Account
                WHERE Affiliate_Number__c = :affiliateNumber
                LIMIT 1
        ];

        return acc;
    }
}