force-app/main/default/objects/Driver__c/fields/Driver_Type__c.field-meta.xml
<CustomField>
    <fullName>Driver_Type__c</fullName>
    <label>Driver Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Co-Owner</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Owner &amp; Driver</fullName>
            </value>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>false</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Broker_Policy_Fee__c.field-meta.xml
<CustomField>
    <fullName>Broker_Policy_Fee__c</fullName>
    <label>Broker/Policy Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/End_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>End_Date_for_Coverage__c</fullName>
    <label>End Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Policy_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Value__c.field-meta.xml
<CustomField>
    <fullName>Quote_Value__c</fullName>
    <label>Quote Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Start_Date_for_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_for_Coverage__c</fullName>
    <label>Start Date for Coverage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Policy_Type_picklist__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>America/Chicago</fullName>
            </value>
            <value>
                <fullName>America/Chihuahua</fullName>
            </value>
            <value>
                <fullName>America/Denver</fullName>
            </value>
            <value>
                <fullName>America/Guatemala</fullName>
            </value>
            <value>
                <fullName>America/Hermosillo</fullName>
            </value>
            <value>
                <fullName>America/Los_Angeles</fullName>
            </value>
            <value>
                <fullName>America/Mazatlan</fullName>
            </value>
            <value>
                <fullName>America/Merida</fullName>
            </value>
            <value>
                <fullName>America/Mexico_City</fullName>
            </value>
            <value>
                <fullName>America/Monterrey</fullName>
            </value>
            <value>
                <fullName>America/New_York</fullName>
            </value>
            <value>
                <fullName>America/Phoenix</fullName>
            </value>
            <value>
                <fullName>America/Tijuana</fullName>
            </value>
            <value>
                <fullName>America/Vancouver</fullName>
            </value>
            <value>
                <fullName>Europe/Amsterdam</fullName>
            </value>
            <value>
                <fullName>Africa/Algiers</fullName>
                <isActive>false</isActive>
                <label>Africa/Algiers</label>
            </value>
            <value>
                <fullName>Africa/Cairo</fullName>
                <isActive>false</isActive>
                <label>Africa/Cairo</label>
            </value>
            <value>
                <fullName>Africa/Johannesburg</fullName>
                <isActive>false</isActive>
                <label>Africa/Johannesburg</label>
            </value>
            <value>
                <fullName>Africa/Nairobi</fullName>
                <isActive>false</isActive>
                <label>Africa/Nairobi</label>
            </value>
            <value>
                <fullName>America/Anchorage</fullName>
                <isActive>false</isActive>
                <label>America/Anchorage</label>
            </value>
            <value>
                <fullName>America/Argentina/Buenos_Aires</fullName>
                <isActive>false</isActive>
                <label>America/Argentina/Buenos_Aires</label>
            </value>
            <value>
                <fullName>America/Bogota</fullName>
                <isActive>false</isActive>
                <label>America/Bogota</label>
            </value>
            <value>
                <fullName>America/Caracas</fullName>
                <isActive>false</isActive>
                <label>America/Caracas</label>
            </value>
            <value>
                <fullName>America/El_Salvador</fullName>
                <isActive>false</isActive>
                <label>America/El_Salvador</label>
            </value>
            <value>
                <fullName>America/Halifax</fullName>
                <isActive>false</isActive>
                <label>America/Halifax</label>
            </value>
            <value>
                <fullName>America/Indiana/Indianapolis</fullName>
                <isActive>false</isActive>
                <label>America/Indiana/Indianapolis</label>
            </value>
            <value>
                <fullName>America/Lima</fullName>
                <isActive>false</isActive>
                <label>America/Lima</label>
            </value>
            <value>
                <fullName>America/Panama</fullName>
                <isActive>false</isActive>
                <label>America/Panama</label>
            </value>
            <value>
                <fullName>America/Puerto_Rico</fullName>
                <isActive>false</isActive>
                <label>America/Puerto_Rico</label>
            </value>
            <value>
                <fullName>America/Santiago</fullName>
                <isActive>false</isActive>
                <label>America/Santiago</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DriverLicenseTermOptionsControllerTest.cls
@isTest
public class DriverLicenseTermOptionsControllerTest {
    @testsetup static void dataSupte(){
             
    }
 @isTest
    static void testMethodOne(){
        DriverLicenseTermOptionsController Drvl = new DriverLicenseTermOptionsController(); 
        DriverLicenseTermOptionsController.getPicklistValues('Driver__c','Driver_Type__c');
        DriverLicenseTermOptionsController.getDependentPicklistValues('Quote__c','Time_Zone__c');
    }
    @isTest
    static void testMethodTwo(){
         Quote__c quote1 = new Quote__c(
            Policy_Type_picklist__c = 'Driver License',
            Quote_Value__c = 130.50,
            Start_Date_for_Coverage__c = Date.today(),
            End_Date_for_Coverage__c = Date.today().addYears(1),
            I_V_A_Mex_Tax__c = 13.50,
            Broker_Policy_Fee__c = 50
            
        );
         insert quote1;
          DriverLicenseTermOptionsController.handleQuoteAction(quote1);
        
         Quote__c quote2 = new Quote__c(
            Policy_Type_picklist__c = 'Driver License',
            Quote_Value__c = 130.50,
            Start_Date_for_Coverage__c = Date.today(),
            End_Date_for_Coverage__c = Date.today().addDays(18),
            I_V_A_Mex_Tax__c = 13.50,
            Broker_Policy_Fee__c = 50
           
        );
         insert quote2;
          DriverLicenseTermOptionsController.handleQuoteAction(quote2);
        
         Quote__c quote3 = new Quote__c(
            Policy_Type_picklist__c = 'Driver License',
            Quote_Value__c = 130.50,
            Start_Date_for_Coverage__c = Date.today(),
            End_Date_for_Coverage__c = Date.today().addDays(60),
            I_V_A_Mex_Tax__c = 13.50,
            Broker_Policy_Fee__c = 50
            
        );
         insert quote3;
          DriverLicenseTermOptionsController.handleQuoteAction(quote3);
         Quote__c quote4 = new Quote__c(
            Policy_Type_picklist__c = 'Driver License',
            Quote_Value__c = 130.50,
            Start_Date_for_Coverage__c = Date.today(),
            End_Date_for_Coverage__c = Date.today().addDays(120),
            I_V_A_Mex_Tax__c = 13.50,
            Broker_Policy_Fee__c = 50
            
        );
         insert quote4;
          DriverLicenseTermOptionsController.handleQuoteAction(quote4);
    }
}