force-app/main/default/objects/Quote__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Value__c.field-meta.xml
<CustomField>
    <fullName>Quote_Value__c</fullName>
    <label>Quote Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Policy_Type_picklist__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Vehicle_Value__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Value__c</fullName>
    <label>Vehicle Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/QuoteTrigger_Test.cls
@isTest
public class QuoteTrigger_Test {
    @isTest
    public static void validateQuoteTrigger(){
        //Create custom setting record for mapping Quote field to Lead field
        QuoteToLeadMapping__c objQuoteToLeadMapping1 = new QuoteToLeadMapping__c();
        objQuoteToLeadMapping1.Name = 'Quote Value';
        objQuoteToLeadMapping1.Lead_API__c='Quote_Value__c';
        objQuoteToLeadMapping1.Quote_API__c='Quote_Value__c';
        insert objQuoteToLeadMapping1;
        
        //Create Lead record
        Lead objLead = new Lead();
        objLead.LastName = 'Test Name';
        objLead.Company = 'Test Company';
        insert objLead;
        
        Test.startTest();
        //Create Quote record
        Quote__c objQuote = new Quote__c();
        objQuote.Lead__c = objLead.Id;
        objQuote.Quote_Value__c = 1122;
        objQuote.Vehicle_Value__c = 6699;
        objQuote.Vehicle_Type__c = 'Mototrcycle';
        insert objQuote;
        
        //Update Quote record fields
        objQuote.Quote_Value__c = 1122;
        objQuote.Vehicle_Value__c = 6699;
        objQuote.Vehicle_Type__c = 'Mototrcycle';
        update objQuote;
        
        //Create Quote record
        Quote__c objQuote2 = new Quote__c();
        objQuote2.Lead__c = objLead.Id;
        objQuote2.Quote_Value__c = 1122;
        objQuote2.Vehicle_Value__c = 6699;
        objQuote2.Vehicle_Type__c = 'Mototrcycle';
        insert objQuote2;
        
        delete objQuote;
        undelete objQuote;
        
        delete objQuote2;
        undelete objQuote2;
        Test.stopTest();
    }

}