force-app/main/default/objects/Contact/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Agent)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies (Agency)</relationshipLabel>
    <relationshipName>Agency</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Policies (Agent)</relationshipLabel>
    <relationshipName>Agent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Net_Premium__c.field-meta.xml
<CustomField>
    <fullName>Net_Premium__c</fullName>
    <label>Net Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Policy_Type_picklist__c.field-meta.xml
<CustomField>
    <fullName>Policy_Type_picklist__c</fullName>
    <label>Policy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automobile</fullName>
            </value>
            <value>
                <fullName>Driver License</fullName>
            </value>
            <value>
                <fullName>Homeowners</fullName>
            </value>
            <value>
                <fullName>Motorcycle/Street Legal ATV</fullName>
            </value>
            <value>
                <fullName>Northbound</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Watercraft</fullName>
            </value>
            <value>
                <fullName>Automobile-Van-Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up</fullName>
            </value>
            <value>
                <fullName>SUV-Crossover</fullName>
            </value>
            <value>
                <fullName>ATV-UTV-Quads-Buggie</fullName>
            </value>
            <value>
                <fullName>Motorcycle</fullName>
            </value>
            <value>
                <fullName>Motorhome</fullName>
            </value>
            <value>
                <fullName>Pickup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/renewed_check__c.field-meta.xml
<CustomField>
    <fullName>renewed_check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>renewed check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Total_Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Transaction_Amount__c</fullName>
    <label>Total Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AgentAppChart.cls
public with sharing class AgentAppChart {
    @AuraEnabled(cacheable=true)
    public static List<Map<String, Object>> getPolicyDataforPieChart(String policyTerm,String userId) {
        if (String.isBlank(userId)) {
            throw new AuraHandledException('Agent or Agency ID cannot be null or empty.');
        }
        List<String> policyTypes = new List<String>{'Automobile-Van-Minivan', 'Motorhome', 'Motorcycle', 'ATV-UTV-Quads-Buggie','SUV-Crossover','Pickup'};
        User userRecord = [SELECT Id, Profile.Name,contactId FROM User WHERE Id = :userId LIMIT 1];
        System.debug('userRecord:::'+userRecord);
        String filterField = userRecord.Profile.Name == 'Agency Community Plus Login User' ? 'Agency__c' : 'Agent__c';
        String contactId = userRecord.contactId;
        String query ='';
        
        if (String.isBlank(policyTerm)) {
            query = 'SELECT Policy_Type_picklist__c,renewed_check__c, COUNT(Id) totalCount ' +
                'FROM Policy__c ' +
                'WHERE ' + filterField + ' = :contactId AND Policy_Type_picklist__c IN: policyTypes ' +
                'GROUP BY Policy_Type_picklist__c,renewed_check__c';
            System.debug('query:::' + query);
        }else{
            query = 'SELECT Policy_Type_picklist__c,renewed_check__c, COUNT(Id) totalCount ' +
                'FROM Policy__c ' +
                'WHERE ' + filterField + ' = :contactId AND Policy_Type_picklist__c IN: policyTypes AND CreatedDate = ' + policyTerm + 
                ' GROUP BY Policy_Type_picklist__c,renewed_check__c';
            System.debug('query:::' + query);
        }
        
        
        
        List<AggregateResult> aggregateResults = Database.query(query);
        List<Map<String, Object>> policyData = new List<Map<String, Object>>();
        
        for (AggregateResult result : aggregateResults) {
            policyData.add(new Map<String, Object>{
                'Policy_Type_picklist__c' => result.get('Policy_Type_picklist__c'),
                    'renewed_check__c' => result.get('renewed_check__c'),
                    'totalCount' => (Integer) result.get('totalCount')
                    });
        }
        System.debug('policyData:::'+policyData);
        return policyData;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Map<String, Object>> getPolicyDataforBarChart(String policyTerm, String userId) {
        if (String.isBlank(userId)) {
            throw new AuraHandledException('Agent or Agency ID cannot be null or empty.');
        }
        List<String> policyTypes = new List<String>{'Automobile-Van-Minivan', 'Motorhome', 'Motorcycle', 'ATV-UTV-Quads-Buggie','SUV-Crossover','Pickup'};
        User userRecord = [SELECT Id, Profile.Name,contactId FROM User WHERE Id = :userId LIMIT 1];
        Contact contactData = new Contact();
        String contactId = userRecord.contactId;
        String query ='';
        
        if(contactId != null){
            contactData = [SELECT id,name,Commission_Mex_Auto_Renew__c, Commission_Mex_Auto_New__c, Commission_Mex_Moto_New__c, Commission_Mex_Moto_Renew__c, Commission_Mex_RV_New__c, Commission_Mex_RV_Renew__c FROM contact WHERE id =:contactId];
        }
        if (String.isBlank(policyTerm)) {
            query = 'SELECT Policy_Type_picklist__c,renewed_check__c, COUNT(Id) totalCount,SUM(Total_Transaction_Amount__c) totalAmount FROM Policy__c WHERE Agency__c = :contactId AND Policy_Type_picklist__c IN: policyTypes GROUP BY Policy_Type_picklist__c,renewed_check__c';
            System.debug('query:::' + query);
        }else{
            query = 'SELECT Policy_Type_picklist__c,renewed_check__c, COUNT(Id) totalCount,SUM(Total_Transaction_Amount__c) totalAmount FROM Policy__c WHERE Agency__c = :contactId  AND Policy_Type_picklist__c IN: policyTypes AND CreatedDate = ' + policyTerm + 
                ' GROUP BY Policy_Type_picklist__c,renewed_check__c';
            System.debug('query:::' + query);
        }
        
        List<AggregateResult> aggregateResults = Database.query(query);
        List<Map<String, Object>> policyData = new List<Map<String, Object>>();
        
        Map<String, Map<Boolean, String>> policyTypeMappings = new Map<String, Map<Boolean, String>>{
            'Automobile' => new Map<Boolean, String>{
                false => 'Commission_Mex_Auto_New__c',
                    true  => 'Commission_Mex_Auto_Renew__c'
                    },
                        'Motorcycle/Street Legal ATV' => new Map<Boolean, String>{
                            false => 'Commission_Mex_Moto_New__c',
                                true  => 'Commission_Mex_Moto_Renew__c'
                                },
                                    'RV' => new Map<Boolean, String>{
                                        false => 'Commission_Mex_RV_New__c',
                                            true  => 'Commission_Mex_RV_Renew__c'
                                            }
        };
            
            for (AggregateResult result : aggregateResults) {
                String policyType = (String) result.get('Policy_Type_picklist__c');
                Boolean isRenewed = (Boolean) result.get('renewed_check__c');
                Decimal totalAmountValue = (Decimal) result.get('totalAmount');
                
                if (policyTypeMappings.containsKey(policyType)) {
                    String commissionField = policyTypeMappings.get(policyType).get(isRenewed);
                    
                    if (!String.isBlank(commissionField) && contactData.get(commissionField) != null) {
                        Decimal commissionValue = (Decimal) contactData.get(commissionField);
                        Double calculatedValue = (totalAmountValue / 100) * commissionValue;
                        System.debug('commissionValue::'+commissionValue);
                        System.debug('totalAmountValue:::'+totalAmountValue); 
                        System.debug('calculatedValue:::'+calculatedValue);
                        policyData.add(new Map<String, Object>{
                            'Policy_Type_picklist__c' => policyType + (isRenewed ? ' Renew' : ' New'),
                                'totalCount' => calculatedValue
                                });
                    }
                }
            }
        
        System.debug('policyData:::' + policyData);
        return policyData;
    }

    @AuraEnabled(cacheable=true)
public static List<Map<String, Object>> getPolicyDataforBarChartNetPremium(String policyTerm, String userId) {
    if (String.isBlank(userId)) {
        throw new AuraHandledException('Agent or Agency ID cannot be null or empty.');
    }

    List<String> policyTypes = new List<String>{'Automobile-Van-Minivan', 'Motorhome', 'Motorcycle'};
    User userRecord = [SELECT Id, Profile.Name, ContactId FROM User WHERE Id = :userId LIMIT 1];
    String contactId = userRecord.ContactId;

    String query = '';
    if (String.isBlank(policyTerm)) {
        query = 'SELECT Policy_Type_picklist__c, renewed_check__c, COUNT(Id) totalCount, SUM(Total_Transaction_Amount__c) totalAmount, SUM(Net_Premium__c) netValue ' +
                'FROM Policy__c ' +
                'WHERE Agency__c = :contactId AND Policy_Type_picklist__c IN :policyTypes ' +
                'GROUP BY Policy_Type_picklist__c, renewed_check__c';
    } else {
        query = 'SELECT Policy_Type_picklist__c, renewed_check__c, COUNT(Id) totalCount, SUM(Total_Transaction_Amount__c) totalAmount, SUM(Net_Premium__c) netValue ' +
                'FROM Policy__c ' +
                'WHERE Agency__c = :contactId AND Policy_Type_picklist__c IN :policyTypes AND CreatedDate = ' + policyTerm + ' ' +
                'GROUP BY Policy_Type_picklist__c, renewed_check__c';
    }

    List<AggregateResult> aggregateResults = Database.query(query);
    List<Map<String, Object>> policyData = new List<Map<String, Object>>();

    for (AggregateResult result : aggregateResults) {
        String policyType = (String) result.get('Policy_Type_picklist__c');
        Boolean isRenewed = (Boolean) result.get('renewed_check__c');
        Decimal totalAmountValue = (Decimal) result.get('netValue');

        // Añadir directamente sin validar comisión
        policyData.add(new Map<String, Object>{
            'Policy_Type_picklist__c' => policyType + (isRenewed ? ' Renew' : ' New'),
            'totalCount' => totalAmountValue
        });
    }

    System.debug('policyData:::' + policyData);
    return policyData;
}

@AuraEnabled(cacheable=true)
public static List<Map<String, Object>> getPolicyDataforBarChartNetPremiumComission(String policyTerm, String userId) {
    if (String.isBlank(userId)) {
        throw new AuraHandledException('Agent or Agency ID cannot be null or empty.');
    }

    List<String> policyTypes = new List<String>{'Automobile-Van-Minivan', 'Motorhome', 'Motorcycle', 'ATV-UTV-Quads-Buggie','SUV-Crossover','Pickup'};
    User userRecord = [SELECT Id, Profile.Name, ContactId FROM User WHERE Id = :userId LIMIT 1];
    String contactId = userRecord.ContactId;

    String query = '';
    if (String.isBlank(policyTerm)) {
        query = 'SELECT Policy_Type_picklist__c, renewed_check__c, COUNT(Id) totalCount, SUM(Total_Transaction_Amount__c) totalAmount, SUM(Net_Premium__c) netValue ' +
                'FROM Policy__c ' +
                'WHERE Agency__c = :contactId AND Policy_Type_picklist__c IN :policyTypes ' +
                'GROUP BY Policy_Type_picklist__c, renewed_check__c';
    } else {
        query = 'SELECT Policy_Type_picklist__c, renewed_check__c, COUNT(Id) totalCount, SUM(Total_Transaction_Amount__c) totalAmount, SUM(Net_Premium__c) netValue ' +
                'FROM Policy__c ' +
                'WHERE Agency__c = :contactId AND Policy_Type_picklist__c IN :policyTypes AND CreatedDate = ' + policyTerm + ' ' +
                'GROUP BY Policy_Type_picklist__c, renewed_check__c';
    }

    List<AggregateResult> aggregateResults = Database.query(query);
List<Map<String, Object>> policyData = new List<Map<String, Object>>();

for (AggregateResult result : aggregateResults) {
    String policyType = (String) result.get('Policy_Type_picklist__c');
    Boolean isRenewed = (Boolean) result.get('renewed_check__c');
    Decimal totalAmountValue = (Decimal) result.get('netValue');

    // Multiplicar el valor por 0.3
    Decimal adjustedValue = totalAmountValue * 0.3;

    policyData.add(new Map<String, Object>{
        'Policy_Type_picklist__c' => policyType + (isRenewed ? ' Renew' : ' New'),
        'totalCount' => adjustedValue
    });
}

System.debug('policyData:::' + policyData);
return policyData;

}
}